Repository penxle/withglyph, pull requests merged in 2023-10, with the labels that each got.

#150 크롬 인풋 자동완성 시 배경색 변하지 않도록 수정
  apps/help.penxle.com/src/styles/base.css
  apps/landing.penxle.com/src/styles/base.css
  apps/penxle.com/src/styles/base.css
  apps/penxle.io/src/styles/base.css
Labels: preview, :rocket:

#144 마케팅 수신 동의 토스트 메시지 길이 줄임
  apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
Labels: :rocket:

#146 클라이언트 사이드에서 인증 실패시킬 수 있는 query 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/enums.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
  apps/penxle.com/src/routes/(default)/me/contentfilters/+page.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page.svelte
Labels: :rocket:

#156 디자인 컬러팔레트 등록
  packages/lib/src/unocss/colors.ts
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#157 버튼 css 수정
  apps/penxle.com/src/lib/components/Button.svelte
Labels: :rocket:

#153 SSO 해제 시 바로 해제하지 않고 컨펌 띄워줌
  apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UserSingleSignOn.svelte
Labels: :rocket:

#154 프로필 수정 버튼 크기 디자인과 통일
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
Labels: :rocket:

#159 glitch에서 svelte 파일 transform할 때 data 프로퍼티 이름 최대한 겹치지 않게 함
  packages/glitch/src/vite/transform-graphql.ts
Labels: :rocket:

#155 구글 아이콘에 여백 제거함
  apps/penxle.com/src/assets/icons/google.svg
Labels: :rocket:

#162 디자인 컬러팔레트 적용
  apps/help.penxle.com/src/styles/base.css
  apps/landing.penxle.com/src/styles/base.css
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/components/Modal.svelte
  apps/penxle.com/src/lib/components/Tag.svelte
  apps/penxle.com/src/lib/components/ToggleButton.svelte
  apps/penxle.com/src/routes/(auth)/login/+page.svelte
  apps/penxle.com/src/routes/(default)/+layout.svelte
  apps/penxle.com/src/routes/(default)/Footer.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/PublishMenu.svelte
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UpdateProfileModal.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UserSingleSignOn.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/deactivate/+page@(default).svelte
  apps/penxle.com/src/routes/(default)/me/activities/Reply.svelte
  apps/penxle.com/src/routes/(default)/me/contentfilters/+page.svelte
  apps/penxle.com/src/routes/(default)/me/followings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/NotificationSwitch.svelte
  apps/penxle.com/src/styles/base.css
  apps/penxle.io/src/styles/base.css
Labels: preview, :rocket:

#152 비밀번호 -> 매직링크 변경
  apps/penxle.com/prisma/migrations/20230925105444_make_user_notification_preference_opt_to_boolean/migration.sql
  apps/penxle.com/prisma/migrations/20230927093759_rename_content_filter_category_all_but_adult_to_trigger/migration.sql
  apps/penxle.com/prisma/migrations/20231002112003_space/migration.sql
  apps/penxle.com/prisma/migrations/20231006064432_space/migration.sql
  apps/penxle.com/prisma/migrations/20231006095008_initialize/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/server/context.ts
  apps/penxle.com/src/lib/server/email/templates/EmailVerification.svelte
  apps/penxle.com/src/lib/server/email/templates/LoginUser.svelte
  apps/penxle.com/src/lib/server/email/templates/PasswordReset.svelte
  apps/penxle.com/src/lib/server/email/templates/PasswordResetRequest.svelte
  apps/penxle.com/src/lib/server/email/templates/Test.svelte
  apps/penxle.com/src/lib/server/email/templates/UpdateUserEmail.svelte
  apps/penxle.com/src/lib/server/email/templates/UserEmailUpdated.svelte
  apps/penxle.com/src/lib/server/email/templates/index.ts
  apps/penxle.com/src/lib/server/enums.ts
  apps/penxle.com/src/lib/server/graphql/schemas/enums.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/rest/handler.ts
  apps/penxle.com/src/lib/server/rest/routes/email.ts
  apps/penxle.com/src/lib/server/rest/routes/index.ts
  apps/penxle.com/src/lib/server/rest/routes/sso.ts
  apps/penxle.com/src/lib/validations/user.ts
  apps/penxle.com/src/routes/(auth)/Header.svelte
  apps/penxle.com/src/routes/(auth)/login/+page.svelte
  apps/penxle.com/src/routes/(auth)/login/code/+page.svelte
  apps/penxle.com/src/routes/(auth)/signup/+page.svelte
  apps/penxle.com/src/routes/(auth)/signup/+page.ts
  apps/penxle.com/src/routes/(auth)/user/forgot-password/+page.svelte
  apps/penxle.com/src/routes/(auth)/user/reset-password/+page.svelte
  apps/penxle.com/src/routes/(auth)/user/verify-email/+page.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UpdateEmailModal.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UpdatePasswordModal.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UpdateProfileModal.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/UserSingleSignOn.svelte
  apps/penxle.com/src/routes/(default)/me/accounts/deactivate/ConfirmModal.svelte
Labels: :rocket:

#161 context finalizer 구현
  apps/penxle.com/src/lib/server/context.ts
  apps/penxle.com/src/lib/server/graphql/handler.ts
  apps/penxle.com/src/lib/server/graphql/plugins/index.ts
  apps/penxle.com/src/lib/server/graphql/plugins/use-context-finalizer.ts
  apps/penxle.com/src/lib/server/rest/handler.ts
Labels: :rocket:

#163 트리거 태그 설명 모달 css 수정
  apps/penxle.com/src/assets/images/content-filtering-example.png
  apps/penxle.com/src/lib/components/Modal.svelte
  apps/penxle.com/src/routes/(default)/me/contentfilters/+page.svelte
Labels: :rocket:

#128 스페이스 초대 기능 구현
  apps/penxle.com/prisma/migrations/20231006095008_initialize/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/validations/common.ts
  apps/penxle.com/src/lib/validations/space.ts
  apps/penxle.com/src/lib/validations/user.ts
  apps/penxle.com/src/routes/(default)/CreateSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/(index)/+page.svelte
Labels: :rocket:

#164 디자인 시스템 폰트 스타일 적용
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#165 prisma 스키마 재생성
  apps/penxle.com/prisma/migrations/20231006104230_initialize/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:

#170 REST API 에러 핸들링 개선
  apps/penxle.com/src/lib/server/graphql/plugins/use-error-handling.ts
  apps/penxle.com/src/lib/server/rest/handler.ts
  apps/penxle.com/src/lib/server/rest/routes/email.ts
  apps/penxle.com/src/lib/server/rest/routes/healthz.ts
  apps/penxle.com/src/lib/server/rest/routes/sso.ts
Labels: :rocket:

#171 누락된 graphql 스키마 업데이트
  apps/penxle.com/schema.graphql
Labels: :rocket:

#172 api 라우트로 이동하는 경우 goto 이용하지 않음
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/routes/(auth)/login/code/+page.svelte
Labels: :rocket:

#169 range slider 컴포넌트 구현
  apps/penxle.com/src/lib/components/forms/Slider.svelte
  apps/penxle.com/src/lib/components/forms/index.ts
  apps/penxle.com/src/routes/_playground/cropper/+page.svelte
Labels: preview, :rocket:

#174 탭 컴포넌트에 링크 추가
  apps/penxle.com/src/lib/components/TabContentItem.svelte
  apps/penxle.com/src/lib/components/TabHead.svelte
  apps/penxle.com/src/lib/components/TabHeadItem.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/lib/components/tab/TabContentItem.svelte
  apps/penxle.com/src/lib/components/tab/TabHead.svelte
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/lib/components/tab/index.ts
  apps/penxle.com/src/routes/(default)/me/activities/+page.svelte
Labels: :rocket:

#173 UserSingleSignOn.principal db 컬럼 매핑 오류 수정
  apps/penxle.com/prisma/migrations/20231007041155_rename_user_single_sign_on_principal/migration.sql
  apps/penxle.com/prisma/migrations/20231007041513_rename_user_single_sign_on_principal/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:

#166 정기 디펜던시 업그레이드
  apps/actions-cache/package.json
  apps/actions-runner/package.json
  apps/bedrock/package.json
  apps/github-app/package.json
  apps/github-app/pulumi/index.ts
  apps/help.penxle.com/package.json
  apps/landing.penxle.com/package.json
  apps/literoom/package.json
  apps/literoom/pulumi/index.ts
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/glitch/package.json
  packages/lambda/package.json
  packages/lambda/src/action/index.ts
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/pulumi/src/components/site.ts
  packages/tracing/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#180 스페이스 초대 mutation들에서 필요한 권한 grant함
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#181 prisma transaction client에 $lock 메서드 추가
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/prisma/transaction.ts
  pnpm-lock.yaml
Labels: :rocket:

#182 백엔드/프론트에서 fetch 대신 각각 got/ky 이용함
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/external-api/google.ts
  apps/penxle.com/src/lib/server/external-api/naver.ts
  apps/penxle.com/src/lib/server/rest/handler.ts
  apps/penxle.com/src/routes/(default)/[space]/publish/artwork/PublishButton.svelte
  pnpm-lock.yaml
Labels: :rocket:

#176 <Thumbnailer /> 컴포넌트 구현
  apps/penxle.com/src/lib/components/media/Thumbnailer.svelte
  apps/penxle.com/src/lib/components/media/index.ts
  apps/penxle.com/src/lib/components/media/thumbnailer.ts
  apps/penxle.com/src/routes/_playground/cropper/+page.svelte
Labels: :rocket:

#178 createMutationForm에 extra 파라메터 추가
  apps/penxle.com/src/lib/form/mutation-form.ts
Labels: :rocket:

#177 이미지 업로드시에 region extraction 기능 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/image.ts
  apps/penxle.com/src/lib/server/utils/image.ts
Labels: :rocket:

#179 유저 프로필 수정 모달에서 프로필 사진 업로드 기능 구현
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/validations/user.ts
  apps/penxle.com/src/routes/(default)/me/accounts/UpdateProfileModal.svelte
Labels: :rocket:

#183 특정 상태의 초대만 볼 수 있도록 쿼리 인수 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#185 스페이스 나가기 gql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#187 스페이스 생성시 전용 프로필 생성할 수 있는 기능 추가
  apps/penxle.com/prisma/migrations/20231011084325_space_member_state/migration.sql
  apps/penxle.com/prisma/migrations/20231011090743_profile_avatar_no_unique/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#190 스페이스 설정 페이지 경로 추가
  apps/penxle.com/src/routes/(default)/[space]/(setting)/dashboard/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/dashboard/+layout.ts
  apps/penxle.com/src/routes/(default)/[space]/(setting)/dashboard/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/posts/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/posts/collections/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/settings/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/settings/(index)/+page.ts
  apps/penxle.com/src/routes/(default)/[space]/(setting)/settings/(index)/DeleteSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/subscribers/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(setting)/subscribers/blocked/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/+layout@.svelte
Labels: :rocket:

#184 나의 펜슬 경로, 레이아웃 변경
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/activities/+page.svelte
  apps/penxle.com/src/routes/(default)/me/activities/Reply.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+page.svelte
  apps/penxle.com/src/routes/(default)/me/comments/+page.svelte
  apps/penxle.com/src/routes/(default)/me/dashboard/+page.svelte
  apps/penxle.com/src/routes/(default)/me/followings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/posts/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+page.ts
  apps/penxle.com/src/routes/(default)/me/settings/UpdateEmailModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UpdateProfileModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UserSingleSignOn.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/+page.ts
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/ContentFilterButton.svelte
  apps/penxle.com/src/routes/(default)/me/settings/deactivate/+page@(default).svelte
  apps/penxle.com/src/routes/(default)/me/settings/deactivate/CompleteModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/deactivate/ConfirmModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/notifications/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/notifications/+page.ts
  apps/penxle.com/src/routes/(default)/me/settings/notifications/NotificationSwitch.svelte
Labels: preview, :rocket:

#189 탭 컴포넌트 링크 클릭 시 바로 이동하도록 수정
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/routes/(default)/[space]/+layout@.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+layout.svelte
Labels: :rocket:

#197 mutation 실패시 toast 등 띄울 수 있도록 관련 훅 glitch에 포함시킴
  apps/penxle.com/src/lib/errors/base.ts
  apps/penxle.com/src/lib/errors/errors.ts
  apps/penxle.com/src/lib/form/mutation-form.ts
  apps/penxle.com/src/lib/glitch/index.ts
  apps/penxle.com/src/routes/(default)/me/settings/UserSingleSignOn.svelte
  packages/glitch/src/client/index.ts
  packages/glitch/src/store/mutation.ts
  packages/glitch/src/store/query.ts
  packages/glitch/src/types.ts
Labels: :rocket:

#200 정기 디펜던시 업그레이드
  apps/actions-cache/package.json
  apps/actions-runner/package.json
  apps/bedrock/package.json
  apps/github-app/package.json
  apps/help.penxle.com/package.json
  apps/landing.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/glitch/package.json
  packages/lambda/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview

#201 actions runner 버전 업데이트
  apps/actions-runner/Dockerfile
Labels: :rocket:

#218 랜덤 스페이스 아이콘 생성 로직 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/playground.ts
  apps/penxle.com/src/lib/server/utils/icon/Template.svelte
  apps/penxle.com/src/lib/server/utils/icon/index.ts
  apps/penxle.com/src/routes/_playground/icons/+page.svelte
  apps/penxle.com/src/routes/_playground/icons/+page.ts
Labels: preview

#224 sans 폰트 Pretendard로 변경
  apps/help.penxle.com/src/routes/[...slug]/+page.svelte
  apps/help.penxle.com/src/service-worker.ts
  apps/help.penxle.com/src/styles/base.css
  apps/help.penxle.com/src/styles/fonts.css
  apps/landing.penxle.com/src/service-worker.ts
  apps/landing.penxle.com/src/styles/base.css
  apps/landing.penxle.com/src/styles/fonts.css
  apps/penxle.com/src/routes/(default)/[space]/publish/post/Editor.svelte
  apps/penxle.com/src/service-worker.ts
  apps/penxle.com/src/styles/base.css
  apps/penxle.com/src/styles/fonts.css
  apps/penxle.io/src/service-worker.ts
  apps/penxle.io/src/styles/base.css
  apps/penxle.io/src/styles/fonts.css
  packages/lib/src/unocss/preset.ts
Labels: preview

#223 정기 디펜던시 업그레이드
  apps/actions-cache/package.json
  apps/actions-runner/package.json
  apps/bedrock/package.json
  apps/github-app/package.json
  apps/help.penxle.com/package.json
  apps/landing.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/glitch/package.json
  packages/lambda/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview
