Repository penxle/withglyph, pull requests merged in 2023-11, with the labels that each got.

#303 이모지 픽커 컴포넌트 구현
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/lib/emoji/data.json
  apps/penxle.com/src/lib/emoji/i18n.json
  apps/penxle.com/src/lib/emoji/index.ts
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  pnpm-lock.yaml
Labels: preview

#325 모바일 토스트 추가
  apps/penxle.com/src/lib/notification/toast/Item.svelte
  apps/penxle.com/src/lib/notification/toast/store.ts
  apps/penxle.com/src/routes/(default)/[space]/dashboard/UpdateSpaceProfileModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UpdateProfileModal.svelte
Labels: :rocket:

#260 메뉴 컴포넌트 추가
  apps/penxle.com/src/lib/components/forms/Select.svelte
  apps/penxle.com/src/lib/components/forms/SelectDivider.svelte
  apps/penxle.com/src/lib/components/forms/SelectOption.svelte
  apps/penxle.com/src/lib/components/forms/index.ts
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/components/menu/index.ts
  pnpm-lock.yaml
Labels: :rocket:

#343 이모지 종류 추가 및 트위모지로 변경
  apps/penxle.com/src/lib/emoji/Emoji.svelte
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/lib/emoji/data.json
  apps/penxle.com/src/lib/emoji/i18n.json
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#340 팁탭 플로팅 메뉴 구현
  apps/penxle.com/src/lib/tiptap/components/TiptapFloatingMenu.svelte
  apps/penxle.com/src/lib/tiptap/components/index.ts
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/index.ts
  apps/penxle.com/src/routes/publish/Editor.svelte
Labels: :rocket:

#336 정기 디펜던시 업그레이드
  apps/actions-cache/package.json
  apps/actions-runner/package.json
  apps/bedrock/package.json
  apps/github-app/package.json
  apps/help.penxle.com/package.json
  apps/landing.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/graphql/handler.ts
  apps/penxle.io/package.json
  package.json
  packages/glitch/package.json
  packages/lambda/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: :rocket:

#339 포스트 미리보기 텍스트 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/tiptap.ts
Labels: :rocket:

#379 비공개 스페이스 설정 gql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#377 포스트 게시옵션 디자인 수정사항 반영
  apps/penxle.com/src/lib/components/ToggleButton.svelte
  apps/penxle.com/src/routes/publish/Header.svelte
Labels: :rocket:

#381 AccessBarrier 코드 살짝 정리
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/index.ts
Labels: :rocket:

#374 불필요한 엘리먼트 래핑 제거
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#386 비공개 스페이스 들어갈 시 오류 throw
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#388 비공개 스페이스 설정, 표시
  apps/penxle.com/src/assets/icons/lock.svg
  apps/penxle.com/src/lib/validations/space.ts
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/SpaceListMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
Labels: :rocket:

#391 에디터 글자수 표시 퍼블리싱
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/routes/publish/Header.svelte
Labels: :rocket:

#390 미리보기를 위해 자기 스페이스의 글은 발행 안 되도 볼 수 있도록 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#392 포스트 미리보기
  apps/penxle.com/src/routes/(default)/[space]/preview/[post]/+page.ts
  apps/penxle.com/src/routes/(default)/[space]/preview/[post]/+page@.svelte
  apps/penxle.com/src/routes/publish/Header.svelte
Labels: :rocket:

#397 탭 컴포넌트에 누락된 스타일 추가
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
Labels: :rocket:

#395 피드 컴포넌트에 태그, 트리거 블러 추가
  apps/penxle.com/src/lib/components/Feed.svelte
Labels: :rocket:

#396 스페이스 홈 페이지에서 Feed 컴포넌트 사용
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
Labels: :rocket:

#398 editable이 false일 때 팁탭 버블 메뉴가 제대로 동작하지 않던 문제 수정
  apps/penxle.com/src/lib/tiptap/components/TiptapBubbleMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#400 스페이스 관심 수/포스트 수 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#405 prisma 쿼리 tracing 시범적으로 추가해봄
  apps/penxle.com/prisma/schema.prisma
  packages/tracing/package.json
  packages/tracing/src/index.ts
  pnpm-lock.yaml
Labels: :rocket:

#407 Revert "prisma 쿼리 tracing 시범적으로 추가해봄 (#405)"
  apps/penxle.com/prisma/schema.prisma
  packages/tracing/package.json
  packages/tracing/src/index.ts
  pnpm-lock.yaml
Labels: :rocket:

#409 updateSpace 인수 nullable하게 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#406 Switch 컴포넌트에 label 추가
  apps/penxle.com/src/lib/components/forms/Switch.svelte
  apps/penxle.com/src/routes/(default)/CreateSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/UpdateSpaceProfileModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
Labels: :rocket:

#408 포스트 패스워드 삭제 기능 추가
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#387 푸터 사업장 주소 변경
  apps/penxle.com/src/routes/(default)/Footer.svelte
Labels: :rocket:

#410 페이지 레이아웃 화면에 꽉 차도록 수정함
  apps/penxle.com/src/routes/(default)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/about/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
Labels: :rocket:

#304 선택 텍스트 이미지 공유 기능 구현하기
  apps/penxle.com/package.json
  apps/penxle.com/src/assets/branding/logo-chalk-transparent.svg
  apps/penxle.com/src/assets/branding/wordmark.svg
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/components/Image.svelte
  apps/penxle.com/src/lib/components/Modal.svelte
  apps/penxle.com/src/lib/tiptap/components/TiptapBubbleMenu.svelte
  apps/penxle.com/src/lib/utils/file.ts
  apps/penxle.com/src/routes/(auth)/Header.svelte
  apps/penxle.com/src/routes/(default)/Footer.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/ShareContent/ColorPicker.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/ShareContent/ShareContent.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/ShareContent/index.ts
  apps/penxle.com/src/styles/prose.css
  pnpm-lock.yaml
Labels: :rocket:

#401 에디터 디자인 수정사항 반영
  apps/penxle.com/src/routes/publish/+page.svelte
  apps/penxle.com/src/routes/publish/Header.svelte
Labels: :rocket:

#402 페이지 title 지정
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/+page.ts
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/(index)/+page.ts
  apps/penxle.com/src/routes/(default)/[space]/dashboard/members/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
Labels: :rocket:

#403 로그인해야 좋아요 누를 수 있도록 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/Toolbar.svelte
Labels: :rocket:

#404 태그 중복 추가 안되도록 수정
  apps/penxle.com/src/routes/publish/+page.svelte
Labels: :rocket:

#418 pothos 플러그인 순서 조정
  apps/penxle.com/src/lib/server/graphql/builder.ts
Labels: :rocket:

#411 포스트 유료분의 이미지/파일 갯수 리턴
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/tiptap.ts
Labels: :rocket:

#414 Post 조회시 space ACTIVE 여부 체크
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#420 유상 포인트 유효기간 1년으로 수정
  apps/help.penxle.com/src/pages/legal/terms.md
Labels: :rocket:

#415 스페이스, 포스트에 빠진 ui 추가함
  apps/penxle.com/src/lib/utils/url.ts
  apps/penxle.com/src/lib/validations/space.ts
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#416 포스트 수정 기능 붙이기
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/components/forms/Switch.svelte
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/glitch/updates.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/publish/+page.svelte
  apps/penxle.com/src/routes/publish/Editor.svelte
  apps/penxle.com/src/routes/publish/Footer.svelte
  apps/penxle.com/src/routes/publish/Header.svelte
  apps/penxle.com/src/routes/publish/[permalink]/+page.svelte
  apps/penxle.com/src/routes/publish/[permalink]/+page.ts
  apps/penxle.com/src/routes/publish/types.ts
Labels: :rocket:

#428 publish 경로 내 폴더 구조 정리
  apps/penxle.com/src/routes/publish/+page.svelte
  apps/penxle.com/src/routes/publish/ColorPaletteButton.svelte
  apps/penxle.com/src/routes/publish/Editor/Editor.svelte
  apps/penxle.com/src/routes/publish/Editor/formats.ts
  apps/penxle.com/src/routes/publish/Editor/index.ts
  apps/penxle.com/src/routes/publish/Header/Header.svelte
  apps/penxle.com/src/routes/publish/Header/ToolbarButton.svelte
  apps/penxle.com/src/routes/publish/Header/index.ts
  apps/penxle.com/src/routes/publish/[permalink]/+page.svelte
Labels: :rocket:

#424 자동저장에도 저장 버튼에서 사용하는 플래그 값을 동일하게 참조하기
  apps/penxle.com/src/routes/publish/Header/Header.svelte
Labels: :rocket:

#425 content.content 필드가 비어 있는 채로 임시저장 시 오류를 응답받아 수정함
  apps/penxle.com/src/routes/publish/Header/Header.svelte
Labels: :rocket:

#426 포스트 임시저장 시 선택한 스페이스가 초기화되는 문제 고치기
  apps/penxle.com/src/routes/publish/Header/Header.svelte
Labels: :rocket:

#427 특정 스페이스로 설정이 필요한 포스트 작성하기 버튼/링크의 URL 수정
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/PublishModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
  apps/penxle.com/src/routes/publish/Header/Header.svelte
Labels: :rocket:

#429 에디터 버블 메뉴 내에 쓰이는 클래스네임 생성이 안되었던 문제 고치기
  apps/penxle.com/src/routes/publish/Editor/Editor.svelte
  apps/penxle.com/src/routes/publish/Editor/formats.svelte
  apps/penxle.com/src/routes/publish/Editor/formats.ts
Labels: :rocket:

#430 버블 메뉴 버튼에 현재 적용한 서식 스타일을 미리 보여주기
  apps/penxle.com/src/routes/publish/Editor/Editor.svelte
  apps/penxle.com/src/routes/publish/Editor/formats.svelte
Labels: :rocket:

#432 포스트 목록 행 정렬을 중앙으로 잘못 되어 있어 고침
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
Labels: :rocket:

#431 에디터 첫 로딩시에는 content가 undefined 상태일 수 있음
  apps/penxle.com/src/routes/publish/+page.svelte
  apps/penxle.com/src/routes/publish/Editor/Editor.svelte
  apps/penxle.com/src/routes/publish/Editor/formats.svelte
  apps/penxle.com/src/routes/publish/Header/Header.svelte
  apps/penxle.com/src/routes/publish/[permalink]/+page.svelte
Labels: :rocket:

#423 포스트 본문 페이지에서 삭제 메뉴 추가하기
  apps/penxle.com/src/lib/glitch/updates.ts
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#434 penxle.com 람다 concurrency 재조정
  apps/penxle.com/pulumi/index.ts
Labels: :rocket:

#433 데이터독 tracing 설정 조정
  apps/literoom/pulumi/index.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#435 포스트 삭제 후 redirect가 안되는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#436 에디터 자잘한 버그 수정
  apps/penxle.com/src/routes/publish/Header/Header.svelte
  apps/penxle.com/src/routes/publish/[permalink]/+page.svelte
Labels: :rocket:

#437 태그에 누락된 flex-gap 스타일 추가
  apps/penxle.com/src/routes/publish/Footer.svelte
Labels: :rocket:

#438 태그 UI 안의 쓰래기통 버튼만 클릭 가능하게 수정함
  apps/penxle.com/src/routes/publish/Footer.svelte
Labels: :rocket:

#441 모바일 레이아웃 깨지는 부분 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/Toolbar.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+page.svelte
  apps/penxle.com/src/routes/(default)/point/purchase/+page.svelte
Labels: :rocket:

#439 정기 디펜던시 업그레이드
  apps/actions-cache/package.json
  apps/actions-runner/package.json
  apps/bedrock/package.json
  apps/github-app/package.json
  apps/help.penxle.com/package.json
  apps/landing.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/glitch/package.json
  packages/glitch/src/types.ts
  packages/lambda/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#442 에디터 일부 버그 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/routes/editor/+page.svelte
  apps/penxle.com/src/routes/editor/Editor.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
Labels: :rocket:

#443 에디터 트리거 설정 관련 버그 수정
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#444 css url path 임시로 절대 주소로 변경함
  apps/penxle.com/src/routes/editor/ArticleFloatingMenu.svelte
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#446 팁탭 이미지/파일 에디터에서 드래그 가능하게 수정
  apps/penxle.com/src/lib/components/Image.svelte
  apps/penxle.com/src/lib/tiptap/node-views/file/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/image/Component.svelte
Labels: :rocket:

#445 회원가입 동의 텍스트 일부 워딩 수정
  apps/penxle.com/src/routes/(auth)/signup/+page.svelte
Labels: :rocket:

#447 팁탭 빈 paragraph 렌더링시에 br 끼워넣음
  apps/penxle.com/src/lib/tiptap/nodes/paragraph.ts
Labels: :rocket:

#448 결제 불가능한 포스트의 경우 "결제선" 문자열 대신 렌더링함
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
Labels: :rocket:

#449 에디터 스페이스 목록 레이아웃 깨지는 문제 해결
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#452 스테이징 환경에서 인용 및 구분선 스타일이 보이지 않아 unocss 에서 일반 css rules 로 빼냄
  apps/penxle.com/src/routes/editor/ArticleFloatingMenu.svelte
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#453 일부 구분선 중앙정렬 적용이 안된 문제 고치기
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#455 스테이징 환경에서 구분선 1, 2, 3 스타일이 보이지 않은 문제 고치기
  apps/penxle.com/src/routes/editor/ArticleFloatingMenu.svelte
  apps/penxle.com/src/styles/prose.css
Labels: preview

#456 피드백 받지 않기로한 경우 이모지 표시하지 못하도록 수정
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/Toolbar.svelte
Labels: :rocket:

#451 결제선에 가격 입력란 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/index.ts
Labels: :rocket:

#460 읽기 소요시간 계산&표시
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/utils/number.ts
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#457 포스트에서 스페이스 정보 클릭 시 스페이스 페이지로 이동
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#458 스페이스 관련 스타일 수정
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/UpdateSpaceProfileModal.svelte
Labels: :rocket:

#459 유저 프로필 변경 모달 hover시 카메라 아이콘 추가
  apps/penxle.com/src/routes/(default)/me/settings/UpdateProfileModal.svelte
Labels: :rocket:

#454 피드백 안받기 설정해도 커스텀 이모지를 달 수 있던 문제 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#461 서버에서 포스트 썸네일 잘라서 저장
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/components/Feed.svelte
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/image.ts
Labels: :rocket:

#464 스페이스 프로필 업데이트 안 되는 문제 해결
  apps/penxle.com/src/routes/(default)/[space]/dashboard/UpdateSpaceProfileModal.svelte
Labels: :rocket:

#468 멤버관리 페이지 모바일에서 아바타 찌그러지는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/dashboard/members/+page.svelte
Labels: :rocket:

#467 이모지 리액션 버튼 아이콘 i-lc-smile-plus로 변경
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
Labels: :rocket:

#465 에디터 하단 스크롤 마진 100px로 조정
  apps/penxle.com/src/routes/editor/ArticleEditor.svelte
Labels: :rocket:

#466 ProseMirror 클래스에 whitespace-pre-wrap 및 break-all 스타일 추가
  apps/penxle.com/src/routes/editor/ArticleEditor.svelte
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#470 에디터 헤더 왼쪽으로 쏠려있는 문제 수정
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: preview

#471 포스트 하단 스타일 디자인에 맞게 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#473 푸터 회사 주소 임시로 되돌림
  apps/penxle.com/src/routes/(default)/Footer.svelte
Labels: :rocket:

#469 포스트 비밀번호에 한글 등을 입력할 수 없게 수정
  apps/penxle.com/src/lib/components/forms/index.ts
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#480 Button red color 추가하기
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/DeleteSpaceModal.svelte
Labels: :rocket:

#472 UpdatePostOption의 contentFilters를 optional화
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#475 스페이스 대시보드 레이아웃 깨지는 부분 수정함
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/SpaceListMenu.svelte
Labels: :rocket:

#477 이름 입력 앞뒤 공백 제거
  apps/penxle.com/src/lib/validations/common.ts
  apps/penxle.com/src/lib/validations/space.ts
Labels: :rocket:

#476 내가 쓴 포스트 필드
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#482 $glitch에 FragmentType 유틸리티 추가
  packages/glitch/src/codegen/entrypoint.ts
  packages/glitch/src/codegen/fragments.ts
  packages/glitch/src/runtime/index.ts
  packages/glitch/src/types.ts
Labels: :rocket:

#305 갤러리 포스트 gql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/routes/editor/+page.svelte
  apps/penxle.com/src/routes/editor/Editor.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
Labels: :rocket:

#487 서버와 클라이언트에서 동일한 ImageBounds 타입 참조하기
  apps/penxle.com/src/lib/components/media/ThumbnailPicker.svelte
  apps/penxle.com/src/lib/components/media/Thumbnailer.svelte
  apps/penxle.com/src/lib/components/media/thumbnailer.ts
  apps/penxle.com/src/lib/server/graphql/schemas/image.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/image.ts
  apps/penxle.com/src/lib/utils/image.ts
Labels: :rocket:

#463 그림 에디터
  apps/penxle.com/package.json
  apps/penxle.com/src/assets/icons/cutting.svg
  apps/penxle.com/src/lib/components/media/Thumbnailer.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/editor/+page.svelte
  apps/penxle.com/src/routes/editor/Editor.svelte
  apps/penxle.com/src/routes/editor/Footer.svelte
  apps/penxle.com/src/routes/editor/GalleryEditor.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
  pnpm-lock.yaml
Labels: :rocket:

#492 포스트 하단에서 스페이스 관심 해제 가능하도록 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#493 포스트 페이지와 미리보기 페이지의 다른 부분 수정함
  apps/penxle.com/src/routes/(default)/[space]/preview/[post]/+page@.svelte
Labels: :rocket:

#489 포스트 게시자만 수정하기 버튼을 보여주기
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#488 ThumbnailPicker 초기 이미지 설정 가능하게 변경
  apps/penxle.com/src/lib/components/media/ThumbnailPicker.svelte
Labels: :rocket:

#500 글 수정할 때 모드 변경할 수 있도록 함
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
Labels: preview

#506 k8s 일부 배포 옵션 수정
  apps/bedrock/pulumi/k8s/kube-system/aws-load-balancer-controller.ts
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#509 자잘한 인프라 설정 정리
  apps/bedrock/pulumi/aws/ec2.ts
  apps/bedrock/pulumi/aws/ecr.ts
  apps/bedrock/pulumi/aws/eks.ts
  apps/bedrock/pulumi/aws/route53.ts
  apps/bedrock/pulumi/aws/vpc.ts
  apps/bedrock/pulumi/k8s/infra/mixpanel-proxy.ts
  apps/bedrock/pulumi/k8s/infra/pgbouncer.ts
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
  apps/bedrock/pulumi/k8s/misc/preview-wildcard.ts
  cspell.config.json
  docker/pgbouncer.dockerfile
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#275 스페이스 포스트 관리 페이지
  apps/penxle.com/src/assets/icons/calender.svg
  apps/penxle.com/src/assets/icons/filter.svg
  apps/penxle.com/src/assets/icons/global.svg
  apps/penxle.com/src/assets/icons/liink.svg
  apps/penxle.com/src/assets/icons/people.svg
  apps/penxle.com/src/assets/icons/trash.svg
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/components/Modal.svelte
  apps/penxle.com/src/lib/components/forms/Checkbox.svelte
  apps/penxle.com/src/lib/components/forms/PopupSearch.svelte
  apps/penxle.com/src/lib/components/forms/index.ts
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
  apps/penxle.com/src/lib/components/pages/index.ts
  apps/penxle.com/src/lib/components/table/Table.svelte
  apps/penxle.com/src/lib/components/table/TableRow.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/members/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/(index)/+page.ts
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+layout.ts
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/collections/+page.svelte
  cspell.config.json
  pnpm-lock.yaml
Labels: :rocket:

#486 Menu UI button element 중첩 제거하기
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
Labels: :rocket:

#490 메뉴 컴포넌트에서 아이템 클릭 시 닫히지 않게 하는 기능 추가하기
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
Labels: :rocket:

#513 tailscale vpc router 커넥션 문제 수정
  apps/bedrock/pulumi/aws/ec2.ts
  apps/bedrock/pulumi/aws/vpc.ts
Labels: :rocket:

#520 argo-rollouts 세팅
  Dockerfile
  apps/bedrock/pulumi/k8s/kube-system/argo-rollouts.ts
  cspell.config.json
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#521 k8s 최소 노드 generation 6 -> 3으로 조정
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
Labels: :rocket:

#522 k8s liveness/readiness probe 세팅
  apps/help.penxle.com/src/routes/api/healthz/+server.ts
  apps/landing.penxle.com/src/routes/api/healthz/+server.ts
  apps/penxle.com/src/lib/server/rest/routes/healthz.ts
  apps/penxle.io/src/routes/api/healthz/+server.ts
  packages/adapter-docker/src/server.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#523 alb/nlb 하나로 통합함
  apps/bedrock/pulumi/k8s/infra/alb.ts
  apps/bedrock/pulumi/k8s/infra/default-backend.ts
  apps/bedrock/pulumi/k8s/infra/mixpanel-proxy.ts
  apps/bedrock/pulumi/k8s/infra/pgbouncer.ts
  apps/bedrock/pulumi/k8s/misc/preview-wildcard.ts
  packages/pulumi/src/components/site.ts
Labels: preview, :rocket:

#525 prerender 비활성화
  apps/help.penxle.com/src/routes/+layout.ts
  apps/landing.penxle.com/src/routes/+layout.ts
  apps/penxle.io/src/routes/+layout.ts
Labels: preview, :rocket:

#526 alb rule 이용해 redirect 재구현
  apps/penxle.com/pulumi/index.ts
  apps/penxle.io/pulumi/index.ts
  packages/pulumi/src/components/redirect.ts
Labels: :rocket:

#547 구분선 항상 커서 이전에 생성되도록 고정하기
  apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
Labels: :rocket:

#540 스페이스 목록 메뉴에서 스페이스 아이콘 보여줌
  apps/penxle.com/src/routes/(default)/[space]/dashboard/SpaceListMenu.svelte
Labels: :rocket:

#516 좋아요한 포스트 목록 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#527 좋아요한 포스트 목록 gql 연결
  apps/penxle.com/src/routes/(default)/me/cabinets/+page.svelte
Labels: :rocket:

#499 숨긴 스페이스 목록
  apps/penxle.com/src/lib/glitch/updates.ts
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
Labels: :rocket:

#238 스페이스 URL 설정 dnd 구현
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
Labels: :rocket:

#530 숨긴 스페이스 진입 시 내용 표시 버튼 보여줌
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
Labels: :rocket:

#498 구매한 포스트 목록 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#507 포스트 구매 시간 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#545 구매한 포스트 목록
  apps/penxle.com/src/lib/components/Feed.svelte
  apps/penxle.com/src/routes/(default)/[space]/purchased/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/purchased/[post]/+page.ts
  apps/penxle.com/src/routes/(default)/me/cabinets/+page.svelte
Labels: :rocket:

#528 AWS opensearch 인프라 정의 추가
  apps/bedrock/pulumi/aws/opensearch.ts
Labels: :rocket:

#548 편집기 권한 문제 hotfix
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#549 opensearch 프로비전 파라메터 변경
  apps/bedrock/pulumi/aws/opensearch.ts
Labels: :rocket:

#551 자잘한 인프라 코드 정리
  apps/bedrock/pulumi/aws/ec2.ts
  apps/bedrock/pulumi/aws/eks.ts
  apps/bedrock/pulumi/k8s/infra/pgbouncer.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#553 OpenSearch 접근권한 열어놓기
  apps/bedrock/pulumi/aws/opensearch.ts
Labels: :rocket:

#555 OpenSearch nori 토크나이저 추가
  apps/bedrock/pulumi/aws/opensearch.ts
  cspell.config.json
Labels: :rocket:

#371 태그 팔로우 gql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#542 사이드바 피드 gql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:
