Repository penxle/withglyph, pull requests merged in 2024-06, with the labels that each got.

#2271 loader dialog가 백버튼 등으로 꺼지는 문제 수정
  apps/mobile/lib/context/loader.dart
Labels: :rocket:

#2272 피드 스크린 구현
  apps/mobile/lib/graphql/feed_screen_query.graphql
  apps/mobile/lib/screens/feed.dart
Labels: :rocket:

#2273 보관함 스크린에서 북마크 없을 시 오류나는 문제 해결
  apps/mobile/lib/screens/archive_bookmarks.dart
Labels: :rocket:

#2274 일부 화면에서 상태바 색상이 오작동하는 문제 해결
  apps/mobile/lib/main.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/login.dart
Labels: :rocket:

#2275 안드로이드와 ios 동작 불일치하는 부분 수정
  apps/mobile/android/app/build.gradle
  apps/mobile/android/app/src/main/AndroidManifest.xml
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2276 shorebird 제거
  apps/mobile/pubspec.yaml
  apps/mobile/shorebird.yaml
Labels: :rocket:

#2277 fastlane 설정
  Gemfile
  Gemfile.lock
  apps/mobile/android/app/build.gradle
  apps/mobile/android/fastlane/Appfile
  apps/mobile/android/fastlane/Fastfile
  apps/mobile/android/fastlane/README.md
  apps/mobile/android/fastlane/metadata/android/ko-KR/full_description.txt
  apps/mobile/android/fastlane/metadata/android/ko-KR/short_description.txt
  apps/mobile/android/fastlane/metadata/android/ko-KR/title.txt
  apps/mobile/android/fastlane/metadata/android/ko-KR/video.txt
  apps/mobile/ios/ExportOptions.plist
  apps/mobile/ios/fastlane/Appfile
  apps/mobile/ios/fastlane/Fastfile
  apps/mobile/ios/fastlane/Matchfile
  apps/mobile/ios/fastlane/README.md
  apps/mobile/package.json
  apps/mobile/pubspec.yaml
  doppler.yaml
Labels: :rocket:

#2278 디펜던시 업그레이드
  Gemfile
  Gemfile.lock
  apps/mobile/.gitignore
  apps/mobile/ios/Podfile.lock
  apps/mobile/ios/fastlane/README.md
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2279 에어브릿지 제거
  apps/mobile/airbridge.json
  apps/mobile/ios/Podfile.lock
  apps/mobile/ios/Runner/AppDelegate.swift
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2280 플러터 master 버전 이용
  apps/mobile/ios/Runner/AppDelegate.swift
  apps/mobile/pubspec.lock
Labels: :rocket:

#2281 코드로 로그인 스크린 구현
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/routers/app.gr.dart
  apps/mobile/lib/screens/feed.dart
  apps/mobile/lib/screens/login_with_code.dart
  apps/mobile/lib/screens/login_with_email.dart
  apps/mobile/lib/screens/login_with_email_next.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2284 뮤테이션 에러 토스트 다시 비활성화
  apps/website/src/lib/glitch/index.ts
Labels: :rocket:

#2289 포스트 관리 필터 셀렉트 박스가 표 헤더 뒤로 가려지는 문제 수정
  apps/website/src/routes/(default)/[space]/dashboard/posts/+page.svelte
Labels: :rocket:

#2290 포스트 관리 테이블에서 preview text도 보여줌
  apps/website/src/routes/(default)/[space]/dashboard/posts/PostManageTable.svelte
Labels: :rocket:

#2282 토스트 포지션 조정
  apps/mobile/ios/Podfile.lock
  apps/mobile/lib/context/toast.dart
Labels: :rocket:

#2283 에러 핸들링 개선
  apps/mobile/lib/ferry/error.dart
  apps/mobile/lib/ferry/error.freezed.dart
  apps/mobile/lib/ferry/extension.dart
  apps/mobile/lib/providers/push_notification.dart
  apps/mobile/lib/providers/push_notification.g.dart
  apps/mobile/lib/screens/login_with_code.dart
Labels: :rocket:

#2285 포스트 스크린에서 포스트 조회 뮤테이션 호출
  apps/mobile/lib/ferry/widget.dart
  apps/mobile/lib/graphql/post_screen_update_post_view_mutation.graphql
  apps/mobile/lib/screens/post.dart
Labels: :rocket:

#2286 에러 스크린 추가
  apps/mobile/lib/app.dart
  apps/mobile/lib/widgets/errror.dart
Labels: :rocket:

#2287 codegen되는 파일 gitignore에 추가
  apps/mobile/.gitignore
  apps/mobile/lib/env.g.dart
  apps/mobile/lib/ferry/error.freezed.dart
  apps/mobile/lib/providers/auth.freezed.dart
  apps/mobile/lib/providers/auth.g.dart
  apps/mobile/lib/providers/ferry.g.dart
  apps/mobile/lib/providers/push_notification.freezed.dart
  apps/mobile/lib/providers/push_notification.g.dart
  apps/mobile/lib/routers/app.gr.dart
Labels: :rocket:

#2288 홈화면 캐러셀 구현
  apps/mobile/lib/screens/home.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2294 ios 앱 스킴 변경
  apps/mobile/ios/Runner/Info.plist
Labels: :rocket:

#2293 PostTagKind.CHALLENGE 추가
  apps/website/drizzle/0015_puzzling_preak.sql
  apps/website/drizzle/meta/0015_snapshot.json
  apps/website/drizzle/meta/_journal.json
  apps/website/src/lib/enums.ts
  cspell.config.json
Labels: :rocket:

#2295 주간챌린지 퍼블리싱
  apps/website/schema.graphql
  apps/website/src/assets/icons/challenge-202406-1.svg
  apps/website/src/lib/validations/post.ts
  apps/website/src/routes/(default)/(feed)/(index)/+page.svelte
  apps/website/src/routes/(default)/(feed)/+layout@.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.ts
  apps/website/src/routes/(default)/(feed)/feed/+page.svelte
  apps/website/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#2296 챌린지 피드 구현
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#2297 주간 챌린지 gql 연결
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/(default)/[space]/PostView.svelte
  apps/website/src/routes/(default)/[space]/TagManageModal.svelte
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
  apps/website/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#2298 메인 피드에 챌린지 피드 표시
  apps/website/src/routes/(default)/(feed)/(index)/+page.svelte
Labels: :rocket:

#2299 캐러셀 업데이트
  apps/website/src/routes/(default)/(feed)/(index)/Carousel.svelte
Labels: :rocket:

#2301 tiptap renderer 엔드포인트가 access barrier 동작과 연결되도록 수정
  apps/mobile/lib/screens/post.dart
  apps/website/src/routes/_webview/tiptap-renderer/+page.svelte
Labels: :rocket:

#2303 yjs indexeddb 제거
  apps/website/src/routes/editor/[permalink]/Editor.svelte
Labels: :rocket:

#2304 공개 스페이스로 전환 버튼 추가
  apps/website/src/routes/(default)/[space]/dashboard/settings/+page.svelte
Labels: :rocket:

#2302 포스트 스크린 1차 구현
  apps/bedrock/pulumi/aws/route53.ts
  apps/mobile/analysis_options.yaml
  apps/mobile/assets/icons/chevron-right.svg
  apps/mobile/assets/icons/dots-vertical.svg
  apps/mobile/assets/icons/heart-filled.svg
  apps/mobile/assets/icons/heart.svg
  apps/mobile/assets/icons/list.svg
  apps/mobile/assets/icons/message.svg
  apps/mobile/assets/icons/mood-heart.svg
  apps/mobile/assets/icons/send-2.svg
  apps/mobile/assets/icons/share-3.svg
  apps/mobile/ios/Podfile.lock
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/components/img.dart
  apps/mobile/lib/components/post_card.dart
  apps/mobile/lib/graphql/post_screen_comments_create_comment_mutation.graphql
  apps/mobile/lib/graphql/post_screen_comments_like_comment_mutation.graphql
  apps/mobile/lib/graphql/post_screen_comments_query.graphql
  apps/mobile/lib/graphql/post_screen_comments_unlike_comment_mutation.graphql
  apps/mobile/lib/graphql/post_screen_query.graphql
  apps/mobile/lib/screens/archive.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/login.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/screens/webview.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/lib/themes/colors.dart
  apps/mobile/lib/widgets/errror.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2306 앱용 웹뷰 로직 추가
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/webview.dart
  apps/website/src/lib/flutter/index.ts
  apps/website/src/routes/(default)/+layout.svelte
  apps/website/src/routes/(default)/me/+layout.svelte
  apps/website/src/routes/+layout.server.ts
  apps/website/src/routes/+layout.ts
Labels: :rocket:

#2305 MY글리프 1차 구현
  apps/mobile/assets/icons/filter-cog.svg
  apps/mobile/assets/icons/pig-money.svg
  apps/mobile/assets/icons/scan.svg
  apps/mobile/ios/Podfile.lock
  apps/mobile/lib/components/toggle_switch.dart
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/graphql/me_screen_query.graphql
  apps/mobile/lib/graphql/settings_screen_query.graphql
  apps/mobile/lib/graphql/settings_screen_update_user_marketing_consent_mutation.graphql
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/oss_licenses.dart
  apps/mobile/lib/screens/oss_licenses_details.dart
  apps/mobile/lib/screens/settings.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2307 안드로이드에서는 onContentSizeChanged 이벤트가 동작하지 않음
  apps/mobile/lib/components/webview.dart
Labels: :rocket:

#2310 태그 스크린 구현
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/graphql/tag_screen_follow_tag_mutation.graphql
  apps/mobile/lib/graphql/tag_screen_query.graphql
  apps/mobile/lib/graphql/tag_screen_unfollow_tag_mutation.graphql
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/tag.dart
Labels: :rocket:

#2308 brand 600 색상 업데이트
  apps/website/src/styles/colors.ts
Labels: :rocket:

#2309 외국인 성인인증 스크립트
  apps/website/scripts/foreign-passport.ts
Labels: :rocket:

#2311 챌린지 피드 조건 추가
  apps/website/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#2312 애플로 로그인 구현
  apps/mobile/assets/icons/apple.svg
  apps/mobile/ios/Podfile.lock
  apps/mobile/ios/Runner/Runner.entitlements
  apps/mobile/lib/screens/login.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
  apps/website/.env
  apps/website/package.json
  apps/website/schema.graphql
  apps/website/src/lib/enums.ts
  apps/website/src/lib/server/external-api/apple.ts
  apps/website/src/lib/server/external-api/index.ts
  apps/website/src/lib/server/external-api/types.ts
  apps/website/src/lib/server/graphql/schemas/user.ts
  apps/website/src/routes/(default)/me/settings/(index)/UserSingleSignOn.svelte
  cspell.config.json
  pnpm-lock.yaml
Labels: :rocket:

#2313 포스트카드 디자인 변경사항 반영
  apps/mobile/lib/components/post_card.dart
  apps/mobile/lib/graphql/fragments/post_card_post.graphql
  apps/mobile/lib/graphql/post_card_bookmark_post_mutation.graphql
  apps/mobile/lib/graphql/post_card_unbookmark_post_mutation.graphql
Labels: :rocket:

#2314 챌린지 도장 임시 구현(일단 1주차만)
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
Labels: :rocket:

#2316 앱 리뷰용 계정 로직 추가
  apps/website/.env
  apps/website/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#2317 Revert "yjs indexeddb 제거 (#2303)"
  apps/website/src/routes/editor/[permalink]/Editor.svelte
Labels: :rocket:

#2321 회원탈퇴 에러 시 토스트 띄움
  apps/website/src/routes/(default)/me/settings/deactivate/ConfirmModal.svelte
Labels: :rocket:

#2322 계정 탈퇴 ui를 다른 ui와 맞춤
  apps/website/src/routes/(default)/me/settings/deactivate/+page@(default).svelte
  apps/website/src/routes/(default)/me/settings/deactivate/CompleteModal.svelte
  apps/website/src/routes/(default)/me/settings/deactivate/ConfirmModal.svelte
Labels: :rocket:

#2324 6월 2주차 챌린지 주제 업데이트
  apps/website/src/assets/icons/challenge-202406-1.svg
  apps/website/src/assets/icons/challenge.svg
  apps/website/src/routes/(default)/(feed)/(index)/+page.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
Labels: :rocket:

#2326 2주차 챌린지 캐러셀 링크 업데이트
  apps/website/src/routes/(default)/(feed)/(index)/Carousel.svelte
Labels: :rocket:

#2325 태그 구독/구독 취소 시 구독자 수 업데이트
  apps/website/src/routes/(default)/tag/[name]/+page.svelte
Labels: :rocket:

#2315 보관함 스크린 디자인 반영
  apps/mobile/lib/screens/archive.dart
  apps/mobile/lib/screens/feed.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/tag.dart
Labels: :rocket:

#2320 mixpanel 트래킹 코드 추가
  apps/mobile/ios/Podfile.lock
  apps/mobile/lib/env.dart
  apps/mobile/lib/graphql/auth_provider_query.graphql
  apps/mobile/lib/main.dart
  apps/mobile/lib/providers/auth.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2327 챌린지 태그 2주차로 수정
  apps/website/src/lib/server/graphql/schemas/feed.ts
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
Labels: :rocket:

#2328 계정탈퇴 취소버튼 클릭 시 계정설정으로 돌아가도록 함
  apps/website/src/routes/(default)/me/settings/deactivate/+page@(default).svelte
Labels: :rocket:

#2331 태그 뮤트 기능 추가
  apps/mobile/assets/icons/volume-3.svg
  apps/mobile/lib/graphql/tag_screen_mute_tag_mutation.graphql
  apps/mobile/lib/graphql/tag_screen_unmute_tag_mutation.graphql
  apps/mobile/lib/screens/tag.dart
  apps/mobile/lib/themes/colors.dart
Labels: :rocket:

#2336 iap rest api endpoint 추가
  apps/website/src/lib/server/rest/handler.ts
  apps/website/src/lib/server/rest/routes/iap.ts
  apps/website/src/lib/server/rest/routes/index.ts
Labels: :rocket:

#2337 iap endpoint의 http method를 post로 변경
  apps/website/src/lib/server/rest/routes/iap.ts
Labels: :rocket:

#2330 프로필 스크린 ui만 우선 구현
  apps/mobile/assets/icons/camera.svg
  apps/mobile/lib/graphql/profile_screen_query.graphql
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/profile.dart
Labels: :rocket:

#2334 커스텀 바텀시트 구현
  apps/mobile/lib/context/bottom_sheet.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/screens/tag.dart
Labels: :rocket:

#2333 인앱결제 1차 구현
  apps/mobile/ios/Podfile.lock
  apps/mobile/ios/Runner.xcodeproj/project.pbxproj
  apps/mobile/lib/app.dart
  apps/mobile/lib/graphql/point_purchase_screen_in_app_purchase_point.graphql
  apps/mobile/lib/main.dart
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/point_purchase.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
  apps/website/schema.graphql
  apps/website/src/lib/enums.ts
  apps/website/src/lib/server/graphql/schemas/point.ts
  apps/website/src/routes/(default)/me/point/(index)/+page.svelte
  apps/website/src/routes/(default)/me/point/charge/+page.svelte
  apps/website/src/routes/(default)/point/purchase/+page.svelte
  apps/website/src/routes/(default)/point/purchase/complete/+page@(default).svelte
Labels: :rocket:

#2338 iap 정보 validation 코드 추가 (안드로이드)
  apps/website/.env
  apps/website/package.json
  apps/website/src/lib/server/external-api/google.ts
  apps/website/src/lib/server/rest/routes/iap.ts
  pnpm-lock.yaml
Labels: :rocket:

#2339 앱 관련 db 스키마 마이그레이션 생성
  apps/website/drizzle/0016_abandoned_betty_brant.sql
  apps/website/drizzle/meta/0016_snapshot.json
  apps/website/drizzle/meta/_journal.json
Labels: :rocket:

#2340 애플 iap notification 출력 방식 변경
  apps/website/src/lib/server/rest/routes/iap.ts
Labels: :rocket:

#2341 댓글의 비밀답글이 댓글 작성자에게 안 보이던 버그 수정
  apps/website/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#2346 IAP 플로우 웹훅에서 직접 요청으로 변경 실험
  apps/mobile/ios/Runner.xcodeproj/project.pbxproj
  apps/mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  apps/mobile/ios/Runner/Configuration.storekit
  apps/mobile/lib/graphql/point_purchase_screen_finalize_in_app_purchase_point.graphql
  apps/mobile/lib/screens/point_purchase.dart
  apps/website/.env
  apps/website/package.json
  apps/website/schema.graphql
  apps/website/src/lib/enums.ts
  apps/website/src/lib/server/external-api/apple.ts
  apps/website/src/lib/server/external-api/google.ts
  apps/website/src/lib/server/graphql/schemas/point.ts
  apps/website/src/lib/server/rest/routes/iap.ts
  pnpm-lock.yaml
Labels: :rocket:

#2342 컬렉션 생성 시 createSpaceCollection 뮤테이션 사용함
  apps/website/src/lib/components/pages/collections/CreateCollectionModal.svelte
  apps/website/src/lib/validations/collection.ts
Labels: :rocket:

#2343 페이지 title 수정 및 추가
  apps/website/src/routes/(default)/me/point/(index)/+page.svelte
  apps/website/src/routes/(default)/me/revenue/(index)/+page.svelte
  apps/website/src/routes/(default)/me/subscribes/+page.svelte
Labels: :rocket:

#2345 챌린지 참여 상태 컴포넌트로 분리함
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/(default)/(feed)/challenge/ChallengeEnrollment.svelte
Labels: :rocket:

#2347 컬렉션 관리 버튼 variant 스페이스 관리와 맞춤
  apps/website/src/routes/(default)/[space]/(space)/collections/[collection]/+page@(default).svelte
Labels: :rocket:

#2344 repeaterjs 제한 임시로 늘림
  cspell.config.json
  package.json
  patches/@repeaterjs__repeater@3.0.6.patch
  pnpm-lock.yaml
Labels: :rocket:

#2350 IAP 성공시 포인트 충전 로직 작성
  apps/mobile/lib/graphql/point_purchase_screen_in_app_purchase_point.graphql
  apps/mobile/lib/screens/point_purchase.dart
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/point.ts
Labels: :rocket:

#2351 1만자를 넘는 HTML 코드는 하이라이팅하지 않게 수정
  apps/website/src/lib/tiptap/node-views/html/index.ts
Labels: :rocket:

#2352 포스트 목록에서 태그 클릭 시 태그 상세 페이지로 이동
  apps/website/src/routes/(default)/(feed)/Post.svelte
  apps/website/src/routes/(default)/(feed)/PostCard.svelte
Labels: :rocket:

#2353 자주 쓰이는 컴포넌트들을 components 폴더로 이동함
  apps/website/src/lib/components/LoginRequireAlert.svelte
  apps/website/src/lib/components/Post.svelte
  apps/website/src/lib/components/PostCard.svelte
  apps/website/src/lib/components/index.ts
  apps/website/src/lib/emoji/EmojiPicker.svelte
  apps/website/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/website/src/routes/(default)/(feed)/(index)/+page.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/(default)/(feed)/feed/+page.svelte
  apps/website/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/website/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/website/src/routes/(default)/[space]/(space)/collections/[collection]/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/(space)/posts/+page.svelte
  apps/website/src/routes/(default)/[space]/PostView.svelte
  apps/website/src/routes/(default)/me/cabinets/(index)/+page.svelte
  apps/website/src/routes/(default)/me/cabinets/emojis/EmojiReactedPost.svelte
  apps/website/src/routes/(default)/me/cabinets/recent/+page.svelte
  apps/website/src/routes/(default)/search/+page.svelte
  apps/website/src/routes/(default)/tag/[name]/+page.svelte
Labels: :rocket:

#2354 사용하지 않는 svg 파일 삭제
  apps/website/src/assets/icons/checkmark.svg
  apps/website/src/assets/icons/dot.svg
  apps/website/src/assets/icons/pencil-underline.svg
  apps/website/src/assets/icons/rating-15-plus.svg
  apps/website/src/assets/icons/rating-20-plus.svg
  apps/website/src/assets/icons/stamp.svg
Labels: :rocket:

#2355 툴팁 아이콘 모두 help-line으로 변경
  apps/website/src/routes/(default)/[space]/CommentInput.svelte
  apps/website/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#2356 IAP 일부 코드 개선
  apps/mobile/lib/screens/point_purchase.dart
Labels: :rocket:

#2335 이미지 피커 & 관련 권한 추가
  apps/mobile/android/app/src/main/AndroidManifest.xml
  apps/mobile/ios/Podfile
  apps/mobile/ios/Podfile.lock
  apps/mobile/ios/Runner/Info.plist
  apps/mobile/ios/fastlane/Fastfile
  apps/mobile/ios/fastlane/README.md
  apps/mobile/lib/screens/profile.dart
  apps/mobile/package.json
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2357 karpenter interruption queue 적용
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
Labels: :rocket:

#2358 애플 심사 리젝된 사유 수정중
  apps/mobile/android/fastlane/Fastfile
  apps/mobile/assets/icons/coin.svg
  apps/mobile/lib/context/bottom_sheet.dart
  apps/mobile/lib/context/dialog.dart
  apps/mobile/lib/graphql/notification_screen_mark_all_notification_as_read_mutation.graphql
  apps/mobile/lib/graphql/notification_screen_mark_notification_as_read_mutation.graphql
  apps/mobile/lib/graphql/notification_screen_query.graphql
  apps/mobile/lib/graphql/point_purchase_screen_query.graphql
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/notification.dart
  apps/mobile/lib/screens/placeholder.dart
  apps/mobile/lib/screens/point_purchase.dart
Labels: :rocket:

#2359 앱 포스트 렌더링 방식 변경 + 결제선 핸들링 추가
  apps/mobile/lib/graphql/post_screen_query.graphql
  apps/mobile/lib/screens/post.dart
  apps/website/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/website/src/routes/_webview/post-view/[permalink]/+page.svelte
  apps/website/src/routes/_webview/post-view/[permalink]/+page.ts
Labels: :rocket:

#2360 플러터 관련 interop에 window.flutter 존재하는지 먼저 체크
  apps/mobile/lib/screens/post.dart
  apps/website/src/lib/flutter/index.ts
Labels: :rocket:

#2361 포인트 결제 방식 웹 & 앱 통합
  apps/mobile/lib/graphql/point_purchase_screen_finalize_in_app_purchase_point.graphql
  apps/mobile/lib/graphql/point_purchase_screen_in_app_purchase_point_mutation.graphql
  apps/mobile/lib/graphql/point_purchase_screen_purchase_point_mutation.graphql
  apps/mobile/lib/graphql/post_screen_query.graphql
  apps/mobile/lib/screens/point_purchase.dart
  apps/mobile/lib/screens/post.dart
  apps/website/drizzle/0017_curly_firedrake.sql
  apps/website/drizzle/meta/0017_snapshot.json
  apps/website/drizzle/meta/_journal.json
  apps/website/schema.graphql
  apps/website/src/lib/enums.ts
  apps/website/src/lib/server/graphql/schemas/point.ts
  apps/website/src/lib/validations/point.ts
  apps/website/src/routes/(default)/me/point/(index)/+page.svelte
  apps/website/src/routes/(default)/me/point/charge/+page.svelte
  apps/website/src/routes/(default)/point/purchase/complete/+page@(default).svelte
Labels: :rocket:

#2362 포인트 구매시 loader 보여줌
  apps/mobile/lib/context/loader.dart
  apps/mobile/lib/screens/point_purchase.dart
  apps/mobile/lib/screens/post.dart
Labels: :rocket:

#2363 IAP 결과 못 받을 경우에 대비한 웹훅 세팅
  apps/website/src/lib/server/external-api/apple.ts
  apps/website/src/lib/server/external-api/google.ts
  apps/website/src/lib/server/rest/routes/iap.ts
Labels: :rocket:

#2364 앱에서는 sso시에 자동으로 회원가입 되도록 함
  apps/website/src/lib/server/graphql/schemas/user.ts
  apps/website/src/lib/server/rest/routes/sso.ts
Labels: :rocket:

#2365 로그인 창 디자인 아주 조금씩 개선
  apps/mobile/android/fastlane/metadata/android/ko-KR/title.txt
  apps/mobile/ios/fastlane/metadata/ko/name.txt
  apps/mobile/ios/fastlane/metadata/secondary_category.txt
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/graphql/login_screen_query.graphql
  apps/mobile/lib/routers/root.dart
  apps/mobile/lib/screens/login.dart
  apps/mobile/lib/screens/login_with_email.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/screens/settings.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/lib/shells/lobby.dart
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/image.ts
  apps/website/src/lib/server/rest/routes/iap.ts
Labels: :rocket:

#2366 로그인 스크린 리뉴얼
  apps/mobile/ios/Podfile.lock
  apps/mobile/lib/components/svg_icon.dart
  apps/mobile/lib/components/text_input_field.dart
  apps/mobile/lib/context/bottom_sheet.dart
  apps/mobile/lib/screens/login.dart
  apps/mobile/lib/screens/login_with_email.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/pubspec.lock
  apps/website/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#2367 에디터 화면 일부 구현
  apps/mobile/ios/Runner/Info.plist
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/env.dart
  apps/mobile/lib/screens/editor.dart
  apps/website/src/routes/editor/[permalink]/Editor.svelte
  apps/website/src/routes/editor/[permalink]/Header.svelte
  apps/website/src/routes/editor/[permalink]/context.ts
Labels: :rocket:

#2368 앱 자잘한 버그 수정
  apps/mobile/lib/context/bottom_sheet.dart
  apps/mobile/lib/graphql/post_screen_comments_query.graphql
  apps/mobile/lib/routers/root.dart
  apps/mobile/lib/screens/editor.dart
  apps/mobile/lib/screens/post.dart
  apps/website/src/routes/editor/[permalink]/DraftListModal.svelte
  apps/website/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#2370 앱 스토어 리스팅 정보 수정
  apps/mobile/android/fastlane/metadata/android/ko-KR/full_description.txt
  apps/mobile/android/fastlane/metadata/android/ko-KR/short_description.txt
  apps/mobile/android/fastlane/metadata/android/ko-KR/title.txt
  apps/mobile/ios/fastlane/metadata/ko/description.txt
  apps/mobile/ios/fastlane/metadata/ko/name.txt
  apps/mobile/ios/fastlane/metadata/ko/subtitle.txt
Labels: :rocket:

#2154 리딤코드 DB
  apps/website/drizzle/0018_stiff_doctor_doom.sql
  apps/website/drizzle/meta/0018_snapshot.json
  apps/website/drizzle/meta/_journal.json
  apps/website/schema.graphql
  apps/website/src/lib/enums.ts
  apps/website/src/lib/server/database/schemas/enums.ts
  apps/website/src/lib/server/database/schemas/tables.ts
Labels: :rocket:, DB 마이그레이션 있음

#2291 리딤코드 퍼블리싱
  apps/website/src/assets/icons/redeem-24.svg
  apps/website/src/assets/icons/redeem-40.svg
  apps/website/src/assets/icons/redeem-65.svg
  apps/website/src/routes/(default)/UserMenu.svelte
  apps/website/src/routes/(default)/[space]/dashboard/+layout.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/create/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/create/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/+layout.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/+layout.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/+layout.svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
  apps/website/src/routes/(default)/me/redeem/+layout.svelte
  apps/website/src/routes/(default)/me/redeem/complete/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/history/+page.svelte
Labels: preview, :rocket:

#2373 form validation + AppError 핸들링 코드 추가
  apps/mobile/lib/components/forms/form_text_field.dart
  apps/mobile/lib/ferry/error.dart
  apps/mobile/lib/ferry/extension.dart
  apps/mobile/lib/screens/login_with_email.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
  apps/website/src/lib/server/graphql/builder.ts
Labels: :rocket:

#2374 이메일 로그인 관련 화면 살짝 리뉴얼
  apps/mobile/lib/components/forms/form_text_field.dart
  apps/mobile/lib/env.dart
  apps/mobile/lib/screens/login_with_code.dart
  apps/mobile/lib/screens/login_with_email_next.dart
Labels: :rocket:

#2378 @_required 중첩시 코드가 잘못 생성되는 문제 해결
  packages/glitch/src/codegen/types.ts
  packages/glitch/src/version.ts
Labels: :rocket:

#2377 bottom menu 구현
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/context/bottom_menu.dart
  apps/mobile/lib/screens/post.dart
Labels: :rocket:

#2375 글 태그 수정 시 자동으로 이번주차 챌린지 태그로 바뀌는 문제 수정
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
Labels: :rocket:

#2369 챌린지 참여 도장 4주차까지 미리 구현
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
Labels: :rocket:

#2379 6월 3주차 챌린지 주제 업데이트
  apps/website/src/assets/icons/challenge.svg
  apps/website/src/lib/server/graphql/schemas/feed.ts
  apps/website/src/routes/(default)/(feed)/(index)/+page.svelte
  apps/website/src/routes/(default)/(feed)/(index)/Carousel.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
Labels: :rocket:

#2383 리딤코드 진입점 주석처리함
  apps/website/src/routes/(default)/UserMenu.svelte
  apps/website/src/routes/(default)/[space]/dashboard/+layout.svelte
  apps/website/src/routes/(default)/me/+layout.svelte
Labels: :rocket:

#2371 리딤코드 DB 수정
  apps/website/drizzle/0019_next_maginty.sql
  apps/website/drizzle/meta/0019_snapshot.json
  apps/website/drizzle/meta/_journal.json
  apps/website/src/lib/server/database/schemas/tables.ts
Labels: :rocket:, DB 마이그레이션 있음

#2381 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/company/package.json
  apps/help/package.json
  apps/literoom/package.json
  apps/mobile/package.json
  apps/website/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  pnpm-lock.yaml
  turbo.json
Labels: preview, :rocket:

#2382 리딤코드 QR 이미지 엔드포인트 추가
  apps/website/src/lib/server/rest/handler.ts
  apps/website/src/lib/server/rest/routes/index.ts
  apps/website/src/lib/server/rest/routes/redeem.ts
Labels: :rocket:

#2380 이것저것 디자인 변경사항 반영
  apps/mobile/assets/icons/chevron-down.svg
  apps/mobile/assets/illustrations/home_menu_1.svg
  apps/mobile/assets/illustrations/home_menu_2.svg
  apps/mobile/assets/illustrations/home_menu_3.svg
  apps/mobile/assets/illustrations/home_menu_4.svg
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/components/post_card.dart
  apps/mobile/lib/components/tag.dart
  apps/mobile/lib/const.dart
  apps/mobile/lib/graphql/home_screen_query.graphql
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/login.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/splash.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/lib/shells/lobby.dart
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2384 페이지네이션 자잘한 버그 수정
  apps/website/src/lib/components/Pagination.svelte
Labels: :rocket:

#2385 모바일 디펜던시 업그레이드
  apps/mobile/pubspec.lock
Labels: :rocket:

#2159 리딤코드 gql
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/index.ts
  apps/website/src/lib/server/graphql/schemas/post.ts
  apps/website/src/lib/server/graphql/schemas/redeem.ts
  apps/website/src/lib/server/graphql/schemas/space.ts
  apps/website/src/lib/server/graphql/schemas/user.ts
  apps/website/src/lib/server/utils/space.ts
Labels: :rocket:

#2372 리딤코드 gql 연결
  apps/website/src/lib/const/redeem.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
  apps/website/src/routes/(default)/me/redeem/complete/+page.ts
  apps/website/src/routes/(default)/me/redeem/complete/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/history/+page.svelte
  apps/website/src/routes/(default)/me/redeem/history/+page.ts
Labels: preview, :rocket:

#2376 리딤코드 디자인 미반영 사항 반영함
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/create/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
Labels: :rocket:

#2386 리딤코드 메뉴 다시 추가
  apps/website/src/routes/(default)/UserMenu.svelte
  apps/website/src/routes/(default)/[space]/dashboard/+layout.svelte
  apps/website/src/routes/(default)/me/+layout.svelte
Labels: :rocket:

#2329 주간 챌린지 스크립트
  apps/website/package.json
  apps/website/scripts/weekly-challenge.ts
  pnpm-lock.yaml
Labels: :rocket:

#2387 리딤코드 gql 필드 추가
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/redeem.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
Labels: :rocket:

#2388 리딤코드 qr 이미지 표시 & 다운로드 기능 추가
  apps/website/src/assets/icons/redeem-24.svg
  apps/website/src/assets/icons/redeem-40.svg
  apps/website/src/assets/icons/redeem-65.svg
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/RedeemCodeQrList.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
Labels: :rocket:

#2389 qr 이미지 사이즈 500x500으로 수정
  apps/website/src/lib/server/rest/routes/redeem.ts
Labels: :rocket:

#2390 리딤코드 관련 empty state 문구 추가
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/me/redeem/history/+page.svelte
Labels: :rocket:

#2391 태그 gql에 썸네일 필드 추가
  apps/website/schema.graphql
  apps/website/src/lib/server/graphql/schemas/tag.ts
Labels: :rocket:

#2392 dart 코드 스타일 포매팅
  apps/mobile/analysis_options.yaml
  apps/mobile/lib/app.dart
  apps/mobile/lib/components/button.dart
  apps/mobile/lib/components/forms/form_text_field.dart
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/components/post_card.dart
  apps/mobile/lib/components/pressable.dart
  apps/mobile/lib/components/pull_to_refresh.dart
  apps/mobile/lib/components/thumbnail_post_card.dart
  apps/mobile/lib/components/toggle_switch.dart
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/context/bottom_menu.dart
  apps/mobile/lib/context/dialog.dart
  apps/mobile/lib/context/loader.dart
  apps/mobile/lib/context/toast.dart
  apps/mobile/lib/ferry/auth_link.dart
  apps/mobile/lib/ferry/client.dart
  apps/mobile/lib/ferry/error.dart
  apps/mobile/lib/ferry/extension.dart
  apps/mobile/lib/ferry/widget.dart
  apps/mobile/lib/main.dart
  apps/mobile/lib/providers/auth.dart
  apps/mobile/lib/providers/push_notification.dart
  apps/mobile/lib/routers/observer.dart
  apps/mobile/lib/routers/root.dart
  apps/mobile/lib/screens/archive.dart
  apps/mobile/lib/screens/editor.dart
  apps/mobile/lib/screens/feed.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/login.dart
  apps/mobile/lib/screens/login_with_code.dart
  apps/mobile/lib/screens/login_with_email.dart
  apps/mobile/lib/screens/login_with_email_next.dart
  apps/mobile/lib/screens/login_with_token.dart
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/notification.dart
  apps/mobile/lib/screens/oss_licenses.dart
  apps/mobile/lib/screens/oss_licenses_details.dart
  apps/mobile/lib/screens/placeholder.dart
  apps/mobile/lib/screens/point_purchase.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/screens/profile.dart
  apps/mobile/lib/screens/settings.dart
  apps/mobile/lib/screens/tag.dart
  apps/mobile/lib/screens/webview.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/lib/shells/lobby.dart
  apps/mobile/lib/widgets/errror.dart
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2393 리딤코드 그룹의 코드를 다 사용하면 state 변경
  apps/website/src/lib/server/graphql/schemas/redeem.ts
  apps/website/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#2394 리딤코드 디자인 수정사항 반영
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/RedeemCodeQrList.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
Labels: :rocket:

#2395 알림 메뉴에 scroll lock 적용
  apps/website/src/routes/(default)/NotificationMenu.svelte
Labels: :rocket:

#2396 멤버공개 글은 리딤코드 등록할 수 없도록 수정
  apps/website/src/lib/server/graphql/schemas/redeem.ts
Labels: :rocket:

#2397 리딤코드 전체적인 워딩 및 플로우 수정
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/+page.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/create/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/RedeemCodeQrList.svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
  apps/website/src/routes/(default)/me/redeem/complete/+page@(default).svelte
Labels: :rocket:

#2399 리딤코드 QR 주소 오타 수정
  apps/website/src/lib/server/graphql/schemas/redeem.ts
Labels: :rocket:

#2400 리딤코드에 mixpanel 추가
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/complete/+page.ts
  apps/website/src/routes/(default)/[space]/dashboard/redeem/(create)/next/+page@(default).svelte
  apps/website/src/routes/(default)/[space]/dashboard/redeem/manage/[redeem]/+page@(default).svelte
  apps/website/src/routes/(default)/me/redeem/(index)/+page.svelte
Labels: :rocket:

#2401 리딤코드 복사 아이콘 색상 gray.400으로 변경
  apps/website/src/routes/(default)/[space]/dashboard/redeem/RedeemCodeQrList.svelte
Labels: :rocket:

#2402 앱 에디터 경험 향상
  apps/mobile/lib/components/webview.dart
  apps/mobile/lib/screens/editor.dart
  apps/website/src/lib/flutter/index.ts
  apps/website/src/routes/+layout.svelte
  apps/website/src/routes/editor/[permalink]/AppEditor.svelte
  apps/website/src/routes/editor/[permalink]/AppHeader.svelte
  apps/website/src/routes/editor/[permalink]/DraftListModal.svelte
  apps/website/src/routes/editor/[permalink]/Editor.svelte
  apps/website/src/routes/editor/[permalink]/MobileEditMenu.svelte
  apps/website/src/routes/editor/[permalink]/PublishMenu.svelte
  apps/website/src/routes/editor/[permalink]/WebEditor.svelte
  apps/website/src/routes/editor/[permalink]/WebHeader.svelte
Labels: :rocket:

#2403 모바일 에디터 포커스 이슈 수정
  apps/website/src/lib/tiptap/nodes/paragraph.ts
  apps/website/src/routes/editor/[permalink]/AppHeader.svelte
  apps/website/src/routes/editor/[permalink]/MobileEditMenu.svelte
  apps/website/src/routes/editor/[permalink]/MobileToolbarButton.svelte
Labels: :rocket:

#2404 모바일 에디터 포커스 이슈 수정 2
  apps/website/src/routes/editor/[permalink]/MobileToolbarButton.svelte
Labels: :rocket:

#2405 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/company/package.json
  apps/help/package.json
  apps/literoom/package.json
  apps/website/package.json
  apps/website/src/lib/components/ColorPicker.svelte
  apps/website/src/lib/components/LoginRequireAlert.svelte
  apps/website/src/lib/server/graphql/schemas/search.ts
  apps/website/src/lib/server/utils/search.ts
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  pnpm-lock.yaml
Labels: :rocket:

#2406 자잘한 코드 업데이트
  apps/website/src/lib/components/Modal.svelte
  apps/website/src/lib/components/Pagination.svelte
  apps/website/src/lib/components/Post.svelte
  apps/website/src/lib/tiptap/nodes/hard-break.ts
Labels: :rocket:

#2412 모바일 search 아이콘 수정
  apps/mobile/assets/icons/search.svg
Labels: :rocket:

#2413 앱 bottom navigation 아이콘 변경
  apps/mobile/assets/icons/archive@2.svg
  apps/mobile/assets/icons/article-filled.svg
  apps/mobile/assets/icons/article@2.svg
  apps/mobile/assets/icons/plus@1.75.svg
  apps/mobile/assets/icons/search@2.svg
  apps/mobile/lib/shells/lobby.dart
  apps/mobile/pubspec.lock
Labels: :rocket:

#2414 앱 로비 스크린들 리뉴얼
  apps/mobile/assets/icons/bell-filled.svg
  apps/mobile/assets/icons/bell.svg
  apps/mobile/lib/graphql/home_screen_query.graphql
  apps/mobile/lib/routers/app.dart
  apps/mobile/lib/screens/archive.dart
  apps/mobile/lib/screens/feed.dart
  apps/mobile/lib/screens/home.dart
  apps/mobile/lib/screens/search.dart
  apps/mobile/lib/shells/lobby.dart
Labels: :rocket:

#2415 fastlane 버전 업데이트
  Gemfile.lock
Labels: :rocket:

#2417 ThumbnailPostCard 디자인 변경사항 반영 및 gql 연결
  apps/mobile/assets/icons/check.svg
  apps/mobile/assets/icons/clock.svg
  apps/mobile/assets/icons/share-2.svg
  apps/mobile/lib/components/thumbnail_post_card.dart
  apps/mobile/lib/graphql/feed_screen_query.graphql
  apps/mobile/lib/graphql/fragments/thumbnail_post_card_post.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_bookmark_post_mutation.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_follow_space_mutation.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_mute_space_mutation.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_unbookmark_post_mutation.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_unfollow_space_mutation.graphql
  apps/mobile/lib/graphql/thumbnail_post_card_unmute_space_mutation.graphql
  apps/mobile/lib/screens/feed.dart
Labels: :rocket:

#2407 작성중이던 임시저장글 삭제 후 새 포스트 작성이 되지 않는 오류 수정
  apps/website/src/routes/editor/[permalink]/DraftListModal.svelte
Labels: :rocket:

#2408 임베드 컴포넌트 디자인 변경사항 반영
  apps/website/src/lib/tiptap/node-views/embed/Component.svelte
Labels: :rocket:

#2409 메인 피드 가로 스크롤 offset 수정
  apps/website/src/routes/(default)/(feed)/(index)/HorizontalScroll.svelte
Labels: :rocket:

#2410 주간창작챌린지 1주차 포인트 지급 스크립트
  apps/website/scripts/202406-event-reward.ts
  apps/website/src/lib/const/event.ts
  apps/website/src/routes/(default)/me/point/(index)/+page.svelte
  apps/website/src/routes/(default)/me/point/charge/+page.svelte
Labels: :rocket:

#2418 ThumbnailPostCard 썸네일이 최대 폭 차지하도록 수정
  apps/mobile/lib/components/thumbnail_post_card.dart
Labels: :rocket:

#2420 자잘한 디자인 변경사항 추가 반영
  apps/mobile/lib/components/heading.dart
  apps/mobile/lib/components/thumbnail_post_card.dart
  apps/mobile/lib/context/bottom_menu.dart
  apps/mobile/lib/graphql/fragments/thumbnail_post_card_post.graphql
  apps/mobile/lib/screens/archive.dart
  apps/mobile/lib/screens/archive_bookmarks.dart
  apps/mobile/lib/screens/archive_comments.dart
  apps/mobile/lib/screens/archive_emojis.dart
  apps/mobile/lib/screens/archive_purchases.dart
  apps/mobile/lib/screens/archive_recents.dart
  apps/mobile/lib/screens/feed.dart
Labels: :rocket:

#2419 스크립트에서 email을 쓸때 svelte를 사용하지 않게 변경
  apps/website/scripts/foreign-passport.ts
  apps/website/src/lib/server/email/index.ts
  apps/website/src/lib/server/email/templates/ForeignPassportCompleted.svelte
  apps/website/src/lib/server/email/templates/ForeignPassportRejected.svelte
  apps/website/src/lib/server/email/templates/index.ts
Labels: :rocket:

#2422 썸네일 표시시 연령 체크
  apps/website/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#2421 주간 창작 2주차 보상 스크립트
  apps/website/scripts/202406-event-reward.ts
Labels: :rocket:

#2423 마이글리프 디자인 반영
  apps/mobile/lib/extensions/int.dart
  apps/mobile/lib/graphql/me_screen_query.graphql
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/search.dart
  apps/mobile/lib/shells/default.dart
  apps/mobile/pubspec.lock
  apps/mobile/pubspec.yaml
Labels: :rocket:

#2424 프로필 변경 페이지 디자인 반영
  apps/mobile/lib/components/button.dart
  apps/mobile/lib/components/forms/form_text_field.dart
  apps/mobile/lib/screens/post.dart
  apps/mobile/lib/screens/profile.dart
Labels: :rocket:

#2425 FloatingBottomSheet 구현
  apps/mobile/lib/components/thumbnail_post_card.dart
  apps/mobile/lib/context/bottom_menu.dart
  apps/mobile/lib/context/bottom_sheet.dart
  apps/mobile/lib/graphql/feed_screen_query.graphql
  apps/mobile/lib/screens/feed.dart
  apps/mobile/lib/screens/post.dart
Labels: :rocket:

#2428 6월 4주차 챌린지 주제 업데이트
  apps/website/src/assets/icons/challenge.svg
  apps/website/src/lib/server/graphql/schemas/feed.ts
  apps/website/src/routes/(default)/(feed)/(index)/Carousel.svelte
  apps/website/src/routes/(default)/(feed)/challenge/+page.svelte
  apps/website/src/routes/editor/[permalink]/ChallengeTag.svelte
Labels: :rocket:

#2426 바텀시트 추가 리뉴얼
  apps/mobile/lib/context/bottom_menu.dart
  apps/mobile/lib/context/bottom_sheet.dart
Labels: :rocket:

#2427 모바일 디펜던시 업그레이드
  apps/mobile/pubspec.lock
Labels: :rocket:

#2430 Img 위젯이 가장 적절한 size와 quality를 선택해 이미지를 가져오도록 개선
  apps/mobile/lib/components/img.dart
  apps/mobile/lib/graphql/notification_screen_query.graphql
  apps/mobile/lib/screens/me.dart
  apps/mobile/lib/screens/notification.dart
Labels: :rocket:
