Repository penxle/withglyph, pull requests merged in 2024-01, with the labels that each got.

#1017 링크에 마우스 올릴 때마다 채널톡 버튼 리로드되는 문제 해결
  apps/penxle.com/src/lib/channel.io/Button.svelte
  apps/penxle.com/src/routes/(default)/Footer.svelte
Labels: :rocket:

#1014 이벤트 핸들러에 타겟 타입 강제하지 않고 정의하기
  apps/penxle.com/src/lib/components/Tag.svelte
  apps/penxle.com/src/lib/components/forms/Checkbox.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/routes/(auth)/signup/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowTagModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedTagModal.svelte
  apps/penxle.com/src/routes/editor/Footer.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1022 관심 태그 피드에서 비공개 스페이스 포스트가 보이는 문제 해결
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#1016 거래내역 프로젝트 cashflow로 리네이밍
  .github/workflows/cd-production.yml
  apps/bedrock/pulumi/aws/dynamodb.ts
  apps/bedrock/pulumi/aws/ecr.ts
  apps/cashflow/Pulumi.prod.yaml
  apps/cashflow/Pulumi.yaml
  apps/cashflow/package.json
  apps/cashflow/pulumi/index.ts
  apps/cashflow/src/handler.ts
  apps/cashflow/src/index.ts
  apps/cashflow/src/seed.ts
  apps/cashflow/tsconfig.json
  apps/cashflow/tsup.config.ts
  apps/nocooc/src/handler.ts
  cspell.config.json
  pnpm-lock.yaml
Labels: :rocket:

#1019 밑줄 공유 UI 에서도 선택 문장 복사 차단하기
  apps/penxle.com/src/lib/tiptap/components/TiptapRenderer.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/ShareContent/ShareContent.svelte
Labels: :rocket:

#1024 디자인 단계에서 누락된 엠티 스테이트 문구 추가하기
  apps/penxle.com/src/lib/components/pages/collections/ManageCollectionModal.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowTagModal.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/purchased/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/recent/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedTagModal.svelte
Labels: :rocket:

#1025 중복된 검색 마크업을 PopupSearch 컴포넌트로 교체하기
  apps/penxle.com/src/lib/components/forms/PopupSearch.svelte
  apps/penxle.com/src/lib/components/pages/collections/ManageCollectionModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/members/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedTagModal.svelte
Labels: :rocket:

#1018 푸터 회사 전화번호 변경
  apps/penxle.com/src/routes/(default)/Footer.svelte
Labels: :rocket:

#1021 포스트 삭제시 컬렉션에서도 삭제되도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1020 에디터 푸터 버튼 가운데 정렬 안맞는 문제 수정
  apps/penxle.com/src/routes/editor/Footer.svelte
Labels: :rocket:

#1023 프론트에서 @prisma/client대신 $glitch에서 타입 import함
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/lib/const/feed.ts
  apps/penxle.com/src/routes/editor/types/restore-revision.ts
Labels: :rocket:

#1028 검색 코드 리팩토링
  apps/penxle.com/src/lib/const/feed.ts
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/+layout.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.ts
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
  apps/penxle.com/src/routes/(default)/search/util.ts
Labels: :rocket:

#1029 컬렉션이 없는 포스트를 삭제할 때 발생하는 오류 긴급 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1026 나의 서랍 - 내 관심 관리 기능에 클릭 가능하다는 힌트 스타일 추가
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
Labels: :rocket:

#1027 나의 서랍 헤딩 마크업 및 글꼴 스타일 업데이트하기
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
Labels: :rocket:

#1030 클립보드에서 여러 개행을 붙여넣기 시 유지하기
  apps/penxle.com/src/lib/tiptap/components/TiptapEditor.svelte
Labels: :rocket:

#947 포스트 본문 색상을 원색에 가까운 시인성 좋은 값으로 바꾸기
  apps/penxle.com/src/routes/editor/formats.svelte
  apps/penxle.com/src/styles/prose.css
  packages/lib/src/unocss/colors.ts
Labels: :rocket:

#1036 성인인증 모달에 뒤로가기 버튼 추가
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1037 라디오 버튼 찌그러지지 않도록 수정
  apps/penxle.com/src/lib/components/forms/Radio.svelte
Labels: :rocket:

#1038 모든 라디오 버튼에 라디오 버튼 컴포넌트 사용
  apps/penxle.com/src/routes/(default)/point/purchase/+page.svelte
  apps/penxle.com/src/routes/(default)/point/purchase/complete/+page.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1034 태그 입력을 submit 이벤트로 관리하기
  apps/penxle.com/src/routes/editor/Footer.svelte
Labels: preview, :rocket:

#1041 수익금 gql 페이지네이션 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1039 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  patches/@vercel__nft@0.24.4.patch
  patches/@vercel__nft@0.26.2.patch
  pnpm-lock.yaml
  syncpack.config.cjs
Labels: preview, :rocket:

#1042 페이지네이션 컴포넌트화
  apps/penxle.com/src/lib/components/Pagination.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
Labels: :rocket:

#1043 에디터에서 연회색 사용이 안되는 문제 고치기
  apps/penxle.com/src/routes/editor/formats.svelte
  apps/penxle.com/src/styles/prose.css
  packages/lib/src/unocss/colors.ts
Labels: preview, :rocket:

#1044 저장 시 revise가 끝난 후 한 번만 publish하게 수정
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1047 ElasticSearch 토크나이저 최적화
  apps/penxle.com/scripts/create-search-index.js
Labels: :rocket:

#1045 프로덕션 환경에서 UnknownError 정보가 노출되는 문제 수정
  apps/penxle.com/src/lib/errors/index.ts
  apps/penxle.com/src/lib/glitch/index.ts
  apps/penxle.com/src/routes/+error.svelte
Labels: :rocket:

#1050 FormField 컴포넌트에서 값이 invalid할 때 테두리 빨간색으로 변경
  apps/penxle.com/src/lib/components/forms/FormField.svelte
Labels: :rocket:

#1053 태그 사용 횟수 유틸리티 함수 구현
  apps/penxle.com/src/lib/server/utils/tag.ts
Labels: :rocket:

#1054 모든 pulumi github action에 refresh/upsert 플래그 추가
  .github/workflows/cd-preview.yml
  .github/workflows/cd-production.yml
  .github/workflows/cd-staging.yml
  .github/workflows/cd-teardown.yml
Labels: :rocket:

#1055 포스트 갯수보다 페이지네이션이 더 많이 생기는 오류 수정
  apps/penxle.com/src/lib/components/Pagination.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
Labels: :rocket:

#1056 @sentry/sveltekit 대신 @sentry/browser 와 @sentry/node 직접 이용함
  apps/penxle.com/package.json
  apps/penxle.com/src/hooks/common.ts
  apps/penxle.com/src/lib/errors/index.ts
  pnpm-lock.yaml
  syncpack.config.cjs
Labels: :rocket:

#1059 Revert "@sentry/sveltekit 대신 @sentry/browser 와 @sentry/node 직접 이용함 (#1056)"
  apps/penxle.com/package.json
  apps/penxle.com/src/hooks/common.ts
  apps/penxle.com/src/lib/errors/index.ts
  pnpm-lock.yaml
Labels: preview, :rocket:

#1061 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  packages/adapter-docker/package.json
  packages/lib/package.json
  packages/lib/src/vite/unocss/preprocess.ts
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  pnpm-lock.yaml
Labels: preview

#1057 TabHeadItem 에서 Trailing Slash 를 색인하지 못하는 문제 고치기
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/routes/(default)/(feed)/+layout@.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+layout.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
  apps/penxle.com/src/routes/(default)/tag/[name]/+layout.svelte
Labels: preview, :rocket:

#1068 도커 이미지 빌드 및 디펜던시 tree-shaking 방식 전면적으로 변경
  .gitignore
  Dockerfile
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/literoom/tsup.config.ts
  apps/penxle.com/package.json
  apps/penxle.com/prisma/index.d.ts
  apps/penxle.com/prisma/index.js
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/src/lib/server/database.ts
  apps/penxle.com/src/lib/server/external-api/types.ts
  apps/penxle.com/src/lib/server/graphql/builder.ts
  apps/penxle.com/src/lib/server/graphql/schemas/enums.ts
  apps/penxle.com/src/lib/server/graphql/schemas/point.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/search.ts
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/prisma/exists.ts
  apps/penxle.com/src/lib/server/prisma/logging.ts
  apps/penxle.com/src/lib/server/prisma/transaction.ts
  apps/penxle.com/src/lib/server/utils/point.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
  apps/penxle.com/src/lib/server/utils/search.ts
  apps/penxle.com/src/lib/server/utils/tiptap.ts
  apps/penxle.com/svelte.config.js
  apps/penxle.io/package.json
  packages/adapter-docker/package.json
  packages/adapter-docker/src/index.ts
  packages/adapter-docker/src/server.ts
  packages/pulumi/package.json
  packages/tracing/package.json
  pnpm-lock.yaml
  turbo.json
Labels: preview, :rocket:

#1072 구매한 글은 삭제되도 보이도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: preview, :rocket:

#1060 검색옵션의 트리거 워닝 메뉴를 접으면 레이아웃이 움직이는 문제 수정
  apps/penxle.com/src/routes/(default)/search/+layout.svelte
Labels: :rocket:

#1065 컬렉션 관리 이미지 미리보기 너비 하드코딩 대신 aspect-ratio 지정하기
  apps/penxle.com/src/lib/components/pages/collections/UpdateCollectionModal.svelte
Labels: :rocket:

#1071 검색 결과 페이지에서 탭 스위칭 시 검색 입력이 리셋되는 버그 고치기
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
Labels: :rocket:

#1074 검색 입력 전송 이후에 이동한 검색 결과 페이지에서 검색 텍스트 초기화되는 버그 고치기
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
Labels: :rocket:

#1046 창작자 인증 뮤테이션 구현
  apps/penxle.com/.env
  apps/penxle.com/prisma/migrations/20240115023446_settlement_identity/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/external-api/coocon.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/aes.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/validations/user.ts
Labels: :rocket:

#1070 [breaking change] 메이저 디펜던시 업그레이드
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/help.penxle.com/src/routes/[...slug]/+page.ts
  apps/help.penxle.com/svelte.config.js
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/components/forms/Select.svelte
  apps/penxle.com/src/lib/components/forms/SelectOption.svelte
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/lib/svelte/actions/focused.ts
  apps/penxle.com/src/lib/svelte/actions/hover.ts
  apps/penxle.com/src/routes/editor/Footer.svelte
  apps/penxle.com/svelte.config.js
  apps/penxle.io/package.json
  apps/penxle.io/svelte.config.js
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lib/src/vite/config.ts
  packages/lib/svelte.config.js
  packages/ui/package.json
  packages/ui/svelte.config.js
  pnpm-lock.yaml
Labels: preview, :rocket:

#1048 유저 탈퇴시 UserSession 전체 삭제 / 세션 가져올 때 유저 state 체크
  apps/penxle.com/src/lib/server/context.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1051 helm 차트 배포할 때 Release 대신 Chart 리소스 이용하도록 함
  apps/bedrock/pulumi/k8s/kube-system/argo-rollouts.ts
  apps/bedrock/pulumi/k8s/kube-system/aws-load-balancer-controller.ts
  apps/bedrock/pulumi/k8s/kube-system/cert-manager.ts
  apps/bedrock/pulumi/k8s/kube-system/external-dns.ts
  apps/bedrock/pulumi/k8s/kube-system/external-secrets.ts
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
  apps/bedrock/pulumi/k8s/kube-system/metrics-server.ts
  apps/bedrock/pulumi/k8s/monitoring/datadog.ts
Labels: :rocket:

#1032 Floating UI 보일러플레이트 코드를 커스텀 Svelte Action 으로 줄이기
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/components/Floating.svelte
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/components/forms/Select.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/lib/svelte-floating-ui/index.ts
  apps/penxle.com/src/lib/tiptap/components/TiptapBubbleMenu.svelte
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/SpaceListMenu.svelte
  apps/penxle.com/src/routes/editor/ArticleCharacterCount.svelte
  apps/penxle.com/src/routes/editor/ArticleLinkEditMenu.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  pnpm-lock.yaml
Labels: :rocket:

#1067 모바일 레이아웃을 고려해서 검색결과 페이지 개선함
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/+layout.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
Labels: preview, :rocket:

#1073 iOS Safari 에서 텍스트 입력 시 자동 확대되는 문제 고치기
  apps/penxle.com/src/app.html
Labels: preview, :rocket:

#1076 검색 바에 input type="search" 지정하기
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/styles/base.css
Labels: :rocket:

#1033 Floating UI arrow 계산 보일러플레이트 코드 묶기
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/svelte-floating-ui/index.ts
  apps/penxle.com/src/routes/(default)/[space]/SelectionBubbleMenu.svelte
  apps/penxle.com/src/routes/editor/ArticleCharacterCount.svelte
  apps/penxle.com/src/routes/editor/ArticleLinkEditMenu.svelte
Labels: :rocket:

#1077 누락된 gql 스키마 업데이트
  apps/penxle.com/schema.graphql
Labels: :rocket:

#1078 포스트 미리보기에서 날짜 잘못 표시되는 오류 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1079 atob 함수를 사용하지 않게 수정
  apps/penxle.com/src/lib/server/utils/aes.ts
Labels: :rocket:

#1080 스페이스 피드에서 스페이스 공개 여부 체크
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#1083 갤러리뷰에서 컨텐츠가 비어있는 경우 핸들링
  apps/penxle.com/src/routes/(default)/[space]/GalleryPost.svelte
Labels: :rocket:

#1084 sentry sourcemap 지원
  .github/workflows/cd-preview.yml
  .github/workflows/cd-production.yml
  .github/workflows/cd-staging.yml
  Dockerfile
  apps/penxle.com/.env
  apps/penxle.com/vite.config.ts
  packages/glitch/src/vite/transform-load.ts
Labels: preview, :rocket:

#1058 Safari 에서 세로 방향으로 긴 이미지의 하단 일부분이 숨겨지는 문제 고치기
  apps/penxle.com/src/lib/components/Image.svelte
Labels: preview, :rocket:

#1086 Tiptap Image node-view에서 __data 없을 시 아무것도 렌더링하지 않음
  apps/penxle.com/src/lib/tiptap/node-views/image/Component.svelte
Labels: :rocket:

#1085 쿠콘 여권인증 API 구현
  apps/penxle.com/src/lib/server/external-api/coocon.ts
Labels: :rocket:

#1088 graphql yoga가 일부 상황에서 context를 이상하게 생성하는 버그 수정
  apps/penxle.com/src/lib/server/graphql/handler.ts
Labels: :rocket:

#1064 github actions role에 필요한 iam 권한 추가
  apps/bedrock/pulumi/aws/iam.ts
Labels: preview, :rocket:

#935 독자 프로필 시스템 구축
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/server/utils/masquerade.ts
  apps/penxle.com/src/lib/utils/index.ts
  apps/penxle.com/src/lib/utils/name.ts
  pnpm-lock.yaml
Labels: :rocket:

#1089 Post.recommendedPosts에서 최근 본 포스트는 추천하지 않도록 수정
  apps/penxle.com/prisma/migrations/20240117075932_post_view_viewed_at_index/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1094 채널톡 통합 연동 버튼 삭제
  apps/penxle.com/.env
  apps/penxle.com/package.json
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/hooks/client.ts
  apps/penxle.com/src/lib/channel.io/Button.svelte
  apps/penxle.com/src/lib/channel.io/index.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/routes/(default)/(feed)/+layout@.svelte
  pnpm-lock.yaml
Labels: :rocket:

#926 알림 gql
  apps/penxle.com/prisma/migrations/20240117084529_notification/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/email/templates/notification/Purchase.svelte
  apps/penxle.com/src/lib/server/email/templates/notification/Subscribe.svelte
  apps/penxle.com/src/lib/server/email/templates/notification/index.ts
  apps/penxle.com/src/lib/server/graphql/schemas/index.ts
  apps/penxle.com/src/lib/server/graphql/schemas/notification.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/server/utils/notification.ts
Labels: :rocket:

#1096 알림 필드 잘못된 이름 변경
  apps/penxle.com/prisma/migrations/20240117085017_notification_actor_rename/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:

#1098 알림 gql 인터페이스 도입
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/notification.ts
Labels: :rocket:

#1091 알림 링크 공통 엔드포인트
  apps/penxle.com/src/lib/server/rest/handler.ts
  apps/penxle.com/src/lib/server/rest/routes/index.ts
  apps/penxle.com/src/lib/server/rest/routes/notification.ts
  apps/penxle.com/src/lib/server/utils/notification.ts
  apps/penxle.com/src/lib/utils/index.ts
  apps/penxle.com/src/lib/utils/notification.ts
Labels: :rocket:

#1095 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/bedrock/tsconfig.json
  apps/cashflow/package.json
  apps/cashflow/tsconfig.json
  apps/help.penxle.com/package.json
  apps/help.penxle.com/tsconfig.json
  apps/literoom/package.json
  apps/literoom/tsconfig.json
  apps/penxle.com/package.json
  apps/penxle.com/tsconfig.json
  apps/penxle.io/package.json
  apps/penxle.io/tsconfig.json
  package.json
  packages/adapter-docker/package.json
  packages/adapter-docker/tsconfig.json
  packages/glitch/package.json
  packages/glitch/tsconfig.json
  packages/lib/package.json
  packages/lib/tsconfig.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/pulumi/tsconfig.json
  packages/tracing/package.json
  packages/tracing/tsconfig.json
  packages/tsconfig/tsconfig.json
  packages/ui/package.json
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1099 라이센스 기간 업데이트
  LICENSE
Labels: preview, :rocket:

#1093 포스트 하단에 추천 게시물 목록 추가
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: preview, :rocket:

#1092 알림 gql 연결
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page.ts
  apps/penxle.com/src/routes/(default)/me/notifications/+page@(default).svelte
Labels: :rocket:

#1100 포스트 조회수 캐시
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1102 불필요한 Tiptap Node Option 제거하기
  apps/penxle.com/src/lib/tiptap/nodes/blockquote.ts
  apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
Labels: :rocket:

#1103 Link Mark 경로가 marks 가 아닌 곳에 있어서 이동함
  apps/penxle.com/src/lib/tiptap/extensions/index.ts
  apps/penxle.com/src/lib/tiptap/marks/index.ts
  apps/penxle.com/src/lib/tiptap/marks/link/helpers/autolink.ts
  apps/penxle.com/src/lib/tiptap/marks/link/helpers/click-handler.ts
  apps/penxle.com/src/lib/tiptap/marks/link/index.ts
  apps/penxle.com/src/lib/tiptap/marks/link/link.ts
  apps/penxle.com/src/lib/tiptap/preset.ts
Labels: :rocket:

#1104 무작위 이름 조합 각 100개까지 추가
  apps/penxle.com/src/lib/utils/name.ts
Labels: :rocket:

#1105 스페이스 관심 해제시 알림 삭제
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#1106 알림 메시지 워딩 수정
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page@(default).svelte
Labels: :rocket:

#1107 포스트 추천 게시물에서 자기 자신이 추천되지 않도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1115 어떤 리비전도 가리키지 않는 PostContent 삭제
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1109 tiptap embed node view 구현
  apps/penxle.com/.env
  apps/penxle.com/prisma/migrations/20240120121128_add_embed_model/migration.sql
  apps/penxle.com/prisma/migrations/20240120123204_make_embed_url_unique/migration.sql
  apps/penxle.com/prisma/migrations/20240120155508_alter_embeds/migration.sql
  apps/penxle.com/prisma/migrations/20240120165507_drop_embeds_site/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/external-api/iframely.ts
  apps/penxle.com/src/lib/server/external-api/index.ts
  apps/penxle.com/src/lib/server/graphql/schemas/embed.ts
  apps/penxle.com/src/lib/server/graphql/schemas/index.ts
  apps/penxle.com/src/lib/server/prisma/logging.ts
  apps/penxle.com/src/lib/server/utils/tiptap.ts
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/embed/index.ts
  apps/penxle.com/src/lib/tiptap/node-views/index.ts
  apps/penxle.com/src/lib/tiptap/preset.ts
  apps/penxle.com/src/styles/prose.css
  cspell.config.json
Labels: preview, :rocket:

#1114 여권 인증 gql
  apps/penxle.com/prisma/migrations/20240124053456_passport_verification/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/rest/routes/identification.ts
  apps/penxle.com/src/lib/validations/common.ts
  apps/penxle.com/src/lib/validations/user.ts
Labels: :rocket:

#1116 여권인증 프론트 구현
  apps/penxle.com/src/lib/validations/common.ts
  apps/penxle.com/src/lib/validations/user.ts
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/VerifyPassportIdentityModal.svelte
Labels: :rocket:

#1112 썸네일 자르기 미리보기 화면에서 이미지 비율을 유지하기
  apps/penxle.com/src/lib/components/media/Thumbnailer.svelte
Labels: :rocket:

#1117 포스트 추천란에 자기 자신 포스트가 보이지 않도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1120 프로덕션에서는 팁탭 Embed 익스텐션 비활성화
  apps/penxle.com/src/lib/tiptap/preset.ts
Labels: :rocket:

#1113 썸네일 자르기 모달을 다시 열였을 때 영역 초기화하기
  apps/penxle.com/src/lib/components/media/ThumbnailPicker.svelte
  apps/penxle.com/src/routes/editor/Footer.svelte
  apps/penxle.com/src/routes/editor/GalleryEditor.svelte
Labels: :rocket:

#1122 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1125 grantScopes 내부 쿼리 데이터로더 패턴으로 최적화
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/context.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/server/utils/loader.ts
  pnpm-lock.yaml
Labels: :rocket:

#1126 PostRevision 데이터로더 최적화
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/loader.ts
Labels: :rocket:

#1110 TabHeadItem query 의존성 주입으로 수정하기
  apps/penxle.com/src/lib/components/tab/TabHead.svelte
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
Labels: preview, :rocket:, 테스트 필요

#1121 TabHead variant 동적으로 반영되게 지원하기
  apps/penxle.com/src/lib/components/tab/TabHead.svelte
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
Labels: :rocket:

#1127 스크립트 실행을 위한 esm loader 구현
  apps/penxle.com/package.json
  apps/penxle.com/scripts/loader/hooks.js
  apps/penxle.com/scripts/loader/register.js
  apps/penxle.com/src/lib/server/logging.ts
  apps/penxle.com/svelte.config.js
Labels: :rocket:

#1128 node v20.11에서 수정된 import hook 실행 순서 버그를 반영함
  apps/penxle.com/package.json
Labels: :rocket:

#1137 dangling contents 삭제 스크립트 퍼포먼스 개선
  apps/penxle.com/package.json
  apps/penxle.com/scripts/delete-dangling-post-content.ts
Labels: :rocket:

#1138 폰트 시스템 변경사항 반영
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#1140 디자인 컬러팔레트 변경사항 반영
  packages/lib/src/unocss/colors.ts
Labels: :rocket:

#1131 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/svelte-floating-ui/index.ts
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1111 tiptap 노드 및 마크 전체 리팩토링
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/utils/tiptap.ts
  apps/penxle.com/src/lib/tiptap/extensions/font-family.ts
  apps/penxle.com/src/lib/tiptap/extensions/index.ts
  apps/penxle.com/src/lib/tiptap/extensions/letter-spacing.ts
  apps/penxle.com/src/lib/tiptap/extensions/line-height.ts
  apps/penxle.com/src/lib/tiptap/extensions/node-id.ts
  apps/penxle.com/src/lib/tiptap/extensions/text-align.ts
  apps/penxle.com/src/lib/tiptap/legacies/font-family.ts
  apps/penxle.com/src/lib/tiptap/legacies/heading.ts
  apps/penxle.com/src/lib/tiptap/legacies/horizontal-rule.ts
  apps/penxle.com/src/lib/tiptap/legacies/index.ts
  apps/penxle.com/src/lib/tiptap/legacies/letter-spacing.ts
  apps/penxle.com/src/lib/tiptap/legacies/line-height.ts
  apps/penxle.com/src/lib/tiptap/legacies/text-align.ts
  apps/penxle.com/src/lib/tiptap/legacies/text-color.ts
  apps/penxle.com/src/lib/tiptap/marks/bold.ts
  apps/penxle.com/src/lib/tiptap/marks/font-color.ts
  apps/penxle.com/src/lib/tiptap/marks/font-family.ts
  apps/penxle.com/src/lib/tiptap/marks/font-size.ts
  apps/penxle.com/src/lib/tiptap/marks/index.ts
  apps/penxle.com/src/lib/tiptap/marks/italic.ts
  apps/penxle.com/src/lib/tiptap/marks/link.ts
  apps/penxle.com/src/lib/tiptap/marks/strike.ts
  apps/penxle.com/src/lib/tiptap/marks/text-color.ts
  apps/penxle.com/src/lib/tiptap/marks/underline.ts
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
  apps/penxle.com/src/lib/tiptap/nodes/blockquote.ts
  apps/penxle.com/src/lib/tiptap/nodes/bullet-list.ts
  apps/penxle.com/src/lib/tiptap/nodes/heading.ts
  apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
  apps/penxle.com/src/lib/tiptap/nodes/index.ts
  apps/penxle.com/src/lib/tiptap/nodes/ordered-list.ts
  apps/penxle.com/src/lib/tiptap/nodes/paragraph.ts
  apps/penxle.com/src/lib/tiptap/preset.ts
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/lib/utils/number.ts
  apps/penxle.com/src/routes/editor/ArticleBubbleMenu.svelte
  apps/penxle.com/src/routes/editor/ArticleFloatingMenu.svelte
  apps/penxle.com/src/routes/editor/formats.svelte
  apps/penxle.com/src/styles/prose.css
  apps/penxle.com/uno.config.ts
  pnpm-lock.yaml
Labels: preview, :rocket:

#1090 팁탭 Ruby 마크 구현
  apps/penxle.com/src/lib/tiptap/marks/index.ts
  apps/penxle.com/src/lib/tiptap/marks/ruby.ts
  apps/penxle.com/src/lib/tiptap/preset.ts
  apps/penxle.com/src/routes/editor/ArticleBubbleMenu.svelte
  apps/penxle.com/src/routes/editor/ArticleEditor.svelte
  apps/penxle.com/src/routes/editor/ArticleRubyEditMenu.svelte
Labels: :rocket:

#1132 .svelte 파일 스크립트에서 import 가능하게 수정
  apps/penxle.com/scripts/loader/hooks.js
Labels: :rocket:

#1133 팁탭 스키마 마이그레이션 스크립트 구현
  apps/penxle.com/package.json
  apps/penxle.com/scripts/migrate-revision-content.ts
  apps/penxle.com/src/lib/tiptap/preset.ts
Labels: :rocket:

#1136 에디터에 나눔바른고딕 및 KoPubWorld 돋움 폰트 추가
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/styles/fonts.css
  cspell.config.json
Labels: preview, :rocket:

#1144 기본 폰트 색상 gray-950으로 변경
  apps/help.penxle.com/src/styles/base.css
  apps/penxle.com/src/styles/base.css
  apps/penxle.io/src/styles/base.css
Labels: :rocket:

#1146 컬러팔레트 변경으로 기존 gray 50 색상이 보이지않는 문제 수정
  apps/help.penxle.com/src/routes/+layout.svelte
  apps/penxle.com/src/lib/components/Badge.svelte
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/components/forms/Slider.svelte
  apps/penxle.com/src/lib/components/media/Thumbnailer.svelte
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/file/Component.svelte
  apps/penxle.com/src/routes/(auth)/login/+page.svelte
  apps/penxle.com/src/routes/(auth)/login/code/+page.svelte
  apps/penxle.com/src/routes/(default)/Footer.svelte
  apps/penxle.com/src/routes/(default)/GotoSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/+error.svelte
  apps/penxle.com/src/routes/_internal/under-maintenance/+page.svelte
Labels: :rocket:

#1145 tabler icon 추가
  cspell.config.json
  packages/lib/package.json
  packages/lib/src/unocss/preset.ts
  pnpm-lock.yaml
Labels: :rocket:

#1142 일부 스타일 새 디자인 시스템 맞춰서 업데이트
  apps/penxle.com/src/styles/prose.css
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#1143 tiptap nodeview 드래그 버그 수정
  apps/penxle.com/src/lib/tiptap/lib/NodeView.svelte
  apps/penxle.com/src/lib/tiptap/lib/renderer.ts
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
Labels: :rocket:

#1141 컬러 피커 컴포넌트 추가하기
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/components/ColorPicker.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/routes/_playground/color/+page.svelte
  apps/penxle.com/src/routes/_playground/color/+page.ts
  cspell.config.json
Labels: :rocket:

#1147 pc 에디터 퍼블리싱
  apps/penxle.com/src/assets/icons/globe-outline.svg
  apps/penxle.com/src/assets/icons/globe-solid.svg
  apps/penxle.com/src/assets/icons/letter-space.svg
  apps/penxle.com/src/assets/icons/line-height.svg
  apps/penxle.com/src/assets/icons/ruby.svg
  apps/penxle.com/src/lib/components/ColorPicker.svelte
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/components/forms/Checkbox.svelte
  apps/penxle.com/src/lib/components/forms/Switch.svelte
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/routes/_playground/color/+page.svelte
  apps/penxle.com/src/routes/editor/+page.svelte
  apps/penxle.com/src/routes/editor/ArticleCharacterCount.svelte
  apps/penxle.com/src/routes/editor/ArticleEditor.svelte
  apps/penxle.com/src/routes/editor/DraftPostModal.svelte
  apps/penxle.com/src/routes/editor/Editor.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
  apps/penxle.com/src/routes/editor/PublishMenuRadioGroup.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
  packages/lib/src/unocss/colors.ts
Labels: preview, :rocket:

#1157 토클 버튼 리스타일링
  apps/penxle.com/src/lib/components/ToggleButton.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/ContentFilterButton.svelte
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1123 에디터 리뉴얼 데이터베이스 설계
  apps/penxle.com/prisma/schema.prisma
  cspell.config.json
Labels: :rocket:, DB 마이그레이션 생성 필요

#1153 팁탭 Embed 노드뷰 신규 디자인 반영
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/embed/index.ts
Labels: :rocket:

#1151 팁탭 File 노드뷰 신규 디자인 반영
  apps/penxle.com/src/lib/tiptap/node-views/file/Component.svelte
Labels: :rocket:

#1159 에디터 툴바 툴팁 변경
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/ToolbarButton.svelte
  apps/penxle.com/src/routes/editor/ToolbarButtonTooltip.svelte
Labels: :rocket:

#1158 db 마이그레이션 생성
  apps/penxle.com/prisma/migrations/20240131144223_alter_posts/migration.sql
  apps/penxle.com/schema.graphql
Labels: :rocket:
