Repository penxle/withglyph, pull requests merged in 2024-03, with the labels that each got.

#1486 이미지 공유 텍스트 제대로 선택되지 않는 버그 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1491 포스트 리비전이 1분마다 새로 저장되도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: preview, :rocket:

#1503 pandacss 잘못 옮겨진 부분 수정
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Slide.svelte
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/+page.svelte
  apps/penxle.com/src/routes/editor/[permalink]/DraftListModal.svelte
Labels: :rocket:

#1502 Post.externalSearchable이 실제로 동작하도록 수정함
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(static)/sitemap.xml/+server.ts
Labels: :rocket:

#1506 알림 뱃지 색상, 위치 변경
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
Labels: :rocket:

#1504 모바일 유저메뉴에서 나의 펜슬 메뉴 페이지로 이동하도록 수정
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
Labels: :rocket:

#1505 모바일 포인트 내역 페이지에서 잔여 포인트도 확인할 수 있도록 수정
  apps/penxle.com/src/routes/(default)/point/+page.svelte
Labels: :rocket:

#1507 수익금 출금 DB 스키마
  apps/penxle.com/prisma/migrations/20240307102111_revenue_withdrawal/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:, DB 마이그레이션 있음

#1509 저장이력 모달 css 적용안된 부분 수정
  apps/penxle.com/src/routes/editor/[permalink]/RevisionListModal.svelte
Labels: :rocket:

#1511 관심 스페이스 목록의 비공개 뱃지 레이아웃 깨지는 문제 수정
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowSpaceModal.svelte
Labels: :rocket:

#1512 버튼 컴포넌트 색상 변경
  apps/penxle.com/src/lib/components/v2/Button.svelte
Labels: :rocket:

#1513 glyph 관련 도메인 및 설정 추가
  .github/workflows/automation-preview-comment.yml
  apps/bedrock/pulumi/aws/acm.ts
  apps/bedrock/pulumi/aws/cloudfront.ts
  apps/bedrock/pulumi/aws/route53.ts
  apps/bedrock/pulumi/aws/s3.ts
  apps/bedrock/pulumi/k8s/misc/preview-wildcard.ts
  apps/bedrock/pulumi/tailscale/key.ts
  apps/penxle.com/pulumi/index.ts
  cspell.config.json
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#1516 저장이력 목록 전체가 선택된 것처럼 보이는 문제 수정
  apps/penxle.com/src/routes/editor/[permalink]/RevisionListModal.svelte
Labels: :rocket:

#1515 검색창 사용성 개선
  apps/penxle.com/src/assets/icons/search.svg
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
Labels: :rocket:

#1517 포스트 미리보기/저장이력 안보이는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
  apps/penxle.com/src/routes/(default)/[space]/CommentInput.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1518 모바일에서 포스트 하단바에 이모지 목록 표시
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1519 검색 인덱스 스크립트 인수 추가
  apps/penxle.com/package.json
  apps/penxle.com/scripts/create-search-index.ts
  pnpm-lock.yaml
Labels: :rocket:

#1520 error 50 색상 잘못들어가있던 오류 수정
  apps/penxle.com/src/styles/colors.ts
Labels: :rocket:

#1521 모바일 검색창에 focus시 검색창이 다시 닫히는 문제 수정
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
Labels: preview, :rocket:

#1510 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1525 구분선 안보이는 문제 수정
  apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
Labels: :rocket:

#1529 disabled 버튼에 hover시에는 배경색 바뀌지 않도록 수정
  apps/penxle.com/src/lib/components/v2/Button.svelte
Labels: :rocket:

#1523 새 FormField 컴포넌트 추가
  apps/penxle.com/src/lib/components/v2/forms/FormField.svelte
  apps/penxle.com/src/lib/components/v2/forms/TextInput.svelte
  apps/penxle.com/src/lib/components/v2/forms/index.ts
Labels: :rocket:

#1532 버튼의 로딩 스피너가 제대로 표시되지 않는 문제 수정
  apps/penxle.com/src/lib/components/Button.svelte
  apps/penxle.com/src/lib/components/v2/Button.svelte
Labels: :rocket:

#1069 수익금 출금 동작 구현
  apps/penxle.com/.env
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
  apps/penxle.com/src/lib/server/utils/slack.ts
  cspell.config.json
Labels: :rocket:

#1522 수익금 출금 빠진 필드 추가
  apps/penxle.com/prisma/migrations/20240312101500_revenue_withdrawal/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
Labels: :rocket:, DB 마이그레이션 있음

#1531 도메인 변경에 따른 일부 도메인 설정 수정
  .github/workflows/automation-preview-comment.yml
  apps/bedrock/pulumi/aws/acm.ts
  apps/bedrock/pulumi/aws/cloudfront.ts
  apps/bedrock/pulumi/aws/ec2.ts
  apps/bedrock/pulumi/aws/elasticache.ts
  apps/bedrock/pulumi/aws/rds.ts
  apps/bedrock/pulumi/aws/route53.ts
  apps/bedrock/pulumi/aws/s3.ts
  apps/bedrock/pulumi/k8s/misc/preview-wildcard.ts
  apps/penxle.com/pulumi/index.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#1537 인프라에서 불필요한 도메인 제거
  apps/bedrock/pulumi/aws/acm.ts
  apps/bedrock/pulumi/aws/cloudfront.ts
  apps/bedrock/pulumi/aws/route53.ts
Labels: :rocket:

#1536 태그 목록 길어졌을 때 태그 수정 버튼이 찌그러지는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1538 스크립트 실행시 모듈 오류 임시 수정
  apps/penxle.com/scripts/202402-event-reward.ts
Labels: :rocket:

#1526 포스트 트렌딩 점수 ES에 저장
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/utils/post.ts
  apps/penxle.com/src/lib/server/utils/search.ts
Labels: :rocket:

#1530 추천 피드 ES 기반으로 수정
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#1539 tsx에서 pandacss import 가능하도록 수정함
  apps/penxle.com/panda.config.ts
  apps/penxle.com/scripts/loader/hooks.js
Labels: :rocket:

#1540 tsx에서 ~icons 경로를 찾지 못하는 문제 수정
  apps/penxle.com/scripts/loader/hooks.js
Labels: :rocket:

#1541 트렌드 점수 계산시 오류 무시
  apps/penxle.com/src/lib/server/utils/search.ts
Labels: :rocket:

#1534 수익금 세금 계산 로직 수정
  apps/penxle.com/prisma/migrations/20240315032525_revenue_withdrawal/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/scripts/revenue-test.ts
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
Labels: :rocket:, DB 마이그레이션 있음

#1542 수수료 계산 함수 공용화
  apps/penxle.com/scripts/revenue-test.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
  apps/penxle.com/src/lib/utils/index.ts
  apps/penxle.com/src/lib/utils/revenue.ts
Labels: :rocket:

#1543 트렌드 점수 계산 로직 오류 무시(진짜)
  apps/penxle.com/src/lib/server/utils/search.ts
Labels: :rocket:

#1544 계좌 소유주 이름 저장 & 마스킹 표시
  apps/penxle.com/prisma/migrations/20240315063141_bank_account_holder_name/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:, DB 마이그레이션 있음

#1545 pandacss size utility가 동작하지 않는 문제 수정
  apps/penxle.com/src/styles/utilities.ts
Labels: :rocket:

#1546 밑줄 이미지 편집 모달을 열고 해당 컨테이너 세로 너비가 줄어들었다 늘어나는 문제 고치기
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
Labels: :rocket:

#1548 공유 이미지 편집 미리보기 이미지 중앙정렬 하기
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
  apps/penxle.com/src/styles/utilities.ts
Labels: :rocket:

#1549 이메일 관련 도메인 변경
  apps/bedrock/pulumi/aws/route53.ts
  apps/bedrock/pulumi/aws/ses.ts
Labels: :rocket:

#1550 css 리셋 스크립트 직접 작성함
  apps/penxle.com/package.json
  apps/penxle.com/panda.config.ts
  apps/penxle.com/postcss.config.js
  apps/penxle.com/src/styles/global.ts
  pnpm-lock.yaml
Labels: :rocket:

#1553 삭제된 포스트 관련 버그 수정
  apps/penxle.com/src/lib/server/graphql/schemas/bookmark.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1555 본 포스트 gql 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1554 추천피드 알고리즘 수정
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
  apps/penxle.com/src/lib/server/utils/search.ts
Labels: :rocket:

#1559 포스트 하단 추천 목록도 추천 피드와 비슷한 알고리즘 사용
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1561 로컬이 아닌 환경에서 es 인덱스를 못 찾는 문제 수정
  apps/penxle.com/src/lib/server/search.ts
Labels: :rocket:

#1560 최근 본 포스트 50개는 추천되지 않도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#1547 정기 출금 관련 gql
  apps/penxle.com/prisma/migrations/20240319030736_withdrawal_config/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
  apps/penxle.com/src/lib/utils/revenue.ts
Labels: :rocket:, DB 마이그레이션 있음

#1052 창작자 인증 구현
  apps/penxle.com/src/assets/icons/bank-002.svg
  apps/penxle.com/src/assets/icons/bank-003.svg
  apps/penxle.com/src/assets/icons/bank-004.svg
  apps/penxle.com/src/assets/icons/bank-007.svg
  apps/penxle.com/src/assets/icons/bank-011.svg
  apps/penxle.com/src/assets/icons/bank-020.svg
  apps/penxle.com/src/assets/icons/bank-023.svg
  apps/penxle.com/src/assets/icons/bank-027.svg
  apps/penxle.com/src/assets/icons/bank-031.svg
  apps/penxle.com/src/assets/icons/bank-032.svg
  apps/penxle.com/src/assets/icons/bank-034.svg
  apps/penxle.com/src/assets/icons/bank-035.svg
  apps/penxle.com/src/assets/icons/bank-045.svg
  apps/penxle.com/src/assets/icons/bank-048.svg
  apps/penxle.com/src/assets/icons/bank-050.svg
  apps/penxle.com/src/assets/icons/bank-071.svg
  apps/penxle.com/src/assets/icons/bank-081.svg
  apps/penxle.com/src/assets/icons/bank-089.svg
  apps/penxle.com/src/assets/icons/bank-090.svg
  apps/penxle.com/src/assets/icons/bank-092.svg
  apps/penxle.com/src/lib/components/forms/TextInput.svelte
  apps/penxle.com/src/lib/components/v2/forms/FormField.svelte
  apps/penxle.com/src/lib/components/v2/forms/TextInput.svelte
  apps/penxle.com/src/lib/validations/user.ts
  apps/penxle.com/src/routes/(default)/me/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
Labels: :rocket:

#1533 수익/출금내역 페이지 퍼블리싱
  apps/penxle.com/src/lib/components/Pagination.svelte
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/MonthlyWithdrawSettingModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/SettlementDetailModal.svelte
Labels: preview, :rocket:

#1551 모바일 바텀시트에 border bottom radius 0 적용
  apps/penxle.com/src/lib/components/v2/Modal.svelte
Labels: :rocket:

#1535 수익금 출금 gql 연결
  apps/penxle.com/src/lib/const/revenue.ts
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/MonthlyWithdrawSettingModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/SettlementDetailModal.svelte
Labels: :rocket:

#1556 ui 폰트 SUIT로 변경
  apps/penxle.com/src/lib/tiptap/components/TiptapEditor.svelte
  apps/penxle.com/src/lib/tiptap/components/TiptapRenderer.svelte
  apps/penxle.com/src/service-worker.ts
  apps/penxle.com/src/styles/fonts.css
  apps/penxle.com/src/styles/fonts.ts
  apps/penxle.com/src/styles/global.ts
Labels: :rocket:

#1552 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/scripts/migrate-revision-content.ts
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/point/purchase/+page.svelte
  apps/penxle.io/package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1562 Post.reactionCount 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1563 포스트 유료 조건 검사 추가
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1566 포스트 추천 3개씩만 하도록
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1564 포스트 좋아요 -> 이모지반응 마이그레이션 스크립트
  apps/penxle.com/scripts/migrate-like-to-reaction.ts
Labels: :rocket:

#1565 이모지 남긴 글 목록, 이모지 갯수 표시
  apps/penxle.com/src/routes/(default)/(index)/PostCard.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
Labels: :rocket:

#1567 결제선 해제 시 가격 정보 비우기
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
Labels: :rocket:

#1568 본인/계좌 인증 플로우 개선 및 정산 관련 워딩 수정
  apps/penxle.com/src/lib/components/v2/forms/TextInput.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/MonthlyWithdrawSettingModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/SettlementDetailModal.svelte
Labels: :rocket:

#1571 창작자 워딩 쓰지 않음
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/utils/revenue.ts
Labels: :rocket:

#1573 출금 후 커밋을 안 하던 문제 수정
  apps/penxle.com/src/lib/server/utils/revenue.ts
Labels: :rocket:

#1574 툴팁 최대 너비 지정
  apps/penxle.com/src/lib/components/Tooltip.svelte
Labels: :rocket:

#1575 즉시출금 모달에서 수수료 잘못 표시하던 문제 수정
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
Labels: :rocket:

#1572 출금 인증시 출금 인증 정보를 리턴하도록 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1581 readme 업데이트
  README.md
Labels: :rocket:

#1580 cdn 주소 pnxl.net에서 glyph.pub으로 변경
  apps/help.penxle.com/src/routes/+layout.svelte
  apps/help.penxle.com/src/service-worker.ts
  apps/help.penxle.com/src/styles/fonts.css
  apps/penxle.com/src/app.html
  apps/penxle.com/src/lib/server/graphql/schemas/file.ts
  apps/penxle.com/src/lib/server/graphql/schemas/image.ts
  apps/penxle.com/src/lib/server/rest/routes/nolt.ts
  apps/penxle.com/src/lib/server/rest/routes/opengraph.ts
  apps/penxle.com/src/lib/server/utils/image.ts
  apps/penxle.com/src/lib/server/utils/tiptap.ts
  apps/penxle.com/src/routes/(default)/(index)/+page.svelte
  apps/penxle.com/src/service-worker.ts
  apps/penxle.com/src/styles/fonts.css
  apps/penxle.io/src/routes/+layout.svelte
  apps/penxle.io/src/service-worker.ts
  apps/penxle.io/src/styles/fonts.css
  cspell.config.json
Labels: :rocket:

#1587 gray scale 색상 일부 변경
  apps/penxle.com/src/styles/colors.ts
Labels: :rocket:

#1576 계좌 인증 모달의 창작자 인증 워딩 수정
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
Labels: :rocket:

#1577 내 수익/출금내역 스타일 잘못 지정되어있던 문제 수정
  apps/penxle.com/src/routes/(default)/me/revenue/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/+page.svelte
Labels: :rocket:

#1578 출금 상세 내역의 id를 대문자로 표시
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/SettlementDetailModal.svelte
Labels: :rocket:

#1584 정산 상세 내역에 즉시 출금 수수료 항목 추가
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/settlement/SettlementDetailModal.svelte
Labels: :rocket:

#1590 포스트 하단의 컬렉션 썸네일 이미지가 늘어나는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1586 모바일에서 피드백 받지 않음 툴팁 위치가 잘못 뜨는 문제 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1588 정기출금 날짜 관련 버그 수정
  apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/utils/revenue.ts
Labels: :rocket:

#1583 karpenter 버전 업그레이드
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
  apps/penxle.com/pulumi/index.ts
Labels: :rocket:

#1593 알람 엠티 스테이트 UI 중앙정렬해서 보여주기
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
Labels: :rocket:

#1591 태그 추천 gql 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
Labels: :rocket:

#1579 버튼 컴포넌트 디자인 리뉴얼 반영하기
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
  apps/penxle.com/src/routes/(default)/[space]/CommentInput.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/SharePostPopover.svelte
  apps/penxle.com/src/routes/(default)/[space]/TagManageModal.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page@.svelte
  apps/penxle.com/src/styles/colors.ts
  apps/penxle.com/src/styles/conditions.ts
Labels: preview

#1606 링크 타입 버튼에 _enabled 내부 스타일 값이 무시되는 문제 고치기
  apps/penxle.com/src/styles/conditions.ts
Labels: :rocket:

#1607 링크 타입 버튼 disabled 상태 지원하기
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/styles/conditions.ts
Labels: :rocket:

#1608 button type 어트리뷰트 명시 누락되어서 추가함
  apps/penxle.com/src/lib/components/v2/Button.svelte
Labels: :rocket:

#1597 크롬 브라우저에서 컬러 슬라이더 입력이 빨간색으로 고정되는 문제 고치기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
Labels: :rocket:

#1599 그라데이션 박스 피커값을 실시간으로 변경 시 모든 색상이 일괄 선택되는 문제 고치기
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1598 크롬 브라우저에서 컬러 입력 박스에 사각형 보더가 나타나는 문제 고치기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
Labels: :rocket:

#1617 내 수익 목록의 포스트 제목에 링크가 잘못들어가있던 오류 수정
  apps/penxle.com/src/routes/(default)/me/revenue/(index)/+page.svelte
Labels: :rocket:

#1604 태그 상세 페이지에서 포스트 목록이 먼저 보이도록 수정
  apps/penxle.com/src/lib/components/PostCard.svelte
  apps/penxle.com/src/lib/components/SpacePostCard.svelte
  apps/penxle.com/src/routes/(default)/(index)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/PostItem.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
  apps/penxle.com/src/routes/(default)/tag/[name]/+layout.svelte
Labels: :rocket:

#1613 로고 리뉴얼 반영하기
  apps/help.penxle.com/src/app.html
  apps/help.penxle.com/src/assets/branding/logo.svg
  apps/help.penxle.com/src/error.html
  apps/help.penxle.com/src/routes/+layout.svelte
  apps/help.penxle.com/static/favicon.ico
  apps/help.penxle.com/static/favicon.svg
  apps/help.penxle.com/static/icons/32x32.png
  apps/help.penxle.com/static/icons/icon.svg
  apps/penxle.com/src/app.html
  apps/penxle.com/src/assets/branding/company-logo.svg
  apps/penxle.com/src/assets/branding/logo-chalk-transparent.svg
  apps/penxle.com/src/assets/branding/logo-empty.svg
  apps/penxle.com/src/assets/branding/logo-floating.svg
  apps/penxle.com/src/assets/branding/logo.svg
  apps/penxle.com/src/assets/branding/wordmark.svg
  apps/penxle.com/src/assets/icons/logo-white.svg
  apps/penxle.com/src/assets/icons/logo.svg
  apps/penxle.com/src/error.html
  apps/penxle.com/src/lib/server/utils/image.ts
  apps/penxle.com/src/routes/(auth)/Header.svelte
  apps/penxle.com/src/routes/(default)/Footer.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/+error.svelte
  apps/penxle.com/src/routes/_internal/under-maintenance/+page.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/preview/+page@.svelte
  apps/penxle.com/static/favicon.ico
  apps/penxle.com/static/favicon.svg
  apps/penxle.com/static/icons/32x32.png
  apps/penxle.com/static/icons/icon.svg
  apps/penxle.io/src/app.html
  apps/penxle.io/src/error.html
Labels: :rocket:

#1595 공용 컴포넌트 디자인 변경사항 반영
  apps/penxle.com/src/lib/components/Badge.svelte
  apps/penxle.com/src/lib/components/Chip.svelte
  apps/penxle.com/src/lib/components/Pagination.svelte
  apps/penxle.com/src/lib/components/PostCard.svelte
  apps/penxle.com/src/lib/components/SpacePostCard.svelte
  apps/penxle.com/src/lib/components/Tag.svelte
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/components/forms/Checkbox.svelte
  apps/penxle.com/src/lib/components/forms/Radio.svelte
  apps/penxle.com/src/lib/components/forms/Switch.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/lib/components/menu/Menu.svelte
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/lib/components/tab/TabHead.svelte
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/lib/components/v2/forms/FormField.svelte
  apps/penxle.com/src/lib/components/v2/forms/TextInput.svelte
  apps/penxle.com/src/lib/svelte/actions/floating.ts
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/RadioGroup.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/about/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/subscribers/blocked/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowTagModal.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/PostItem.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+layout.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedTagModal.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/+layout.svelte
  apps/penxle.com/src/routes/(default)/search/post/+page.svelte
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/search/tag/+page.svelte
  apps/penxle.com/src/routes/(default)/tag/[name]/+layout.svelte
  apps/penxle.com/src/routes/editor/[permalink]/DraftListModal.svelte
  apps/penxle.com/src/routes/editor/[permalink]/RadioGroup.svelte
  apps/penxle.com/src/routes/editor/[permalink]/RevisionListModal.svelte
  apps/penxle.com/src/styles/colors.ts
  apps/penxle.com/src/styles/global.ts
Labels: :rocket:

#1609 Select 컴포넌트 추가
  apps/penxle.com/src/lib/components/v2/select/Select.svelte
  apps/penxle.com/src/lib/components/v2/select/SelectItem.svelte
  apps/penxle.com/src/lib/components/v2/select/index.ts
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1610 토스트 컴포넌트 리뉴얼 및 기존 success 상태 토스트 삭제
  apps/penxle.com/src/lib/components/PostCard.svelte
  apps/penxle.com/src/lib/components/pages/collections/CreateCollectionModal.svelte
  apps/penxle.com/src/lib/components/pages/collections/ManageCollectionModal.svelte
  apps/penxle.com/src/lib/components/pages/collections/UpdateCollectionModal.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/lib/glitch/index.ts
  apps/penxle.com/src/lib/notification/toast/Item.svelte
  apps/penxle.com/src/lib/notification/toast/Provider.svelte
  apps/penxle.com/src/lib/notification/toast/store.ts
  apps/penxle.com/src/lib/utils/image.ts
  apps/penxle.com/src/lib/utils/url.ts
  apps/penxle.com/src/routes/(default)/CreateSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/[entity]/+page@(default).svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
  apps/penxle.com/src/routes/(default)/[space]/SharePostPopover.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/UpdateSpaceProfileModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/collections/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/FollowTagModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UpdateEmailModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UpdateProfileModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UserSingleSignOn.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedTagModal.svelte
  apps/penxle.com/src/routes/(default)/point/purchase/+page.svelte
  apps/penxle.com/src/routes/(default)/point/purchase/complete/+page.svelte
  apps/penxle.com/src/routes/(default)/search/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/search/space/+page.svelte
  apps/penxle.com/src/routes/(default)/tag/[name]/+layout.svelte
  apps/penxle.com/src/routes/+layout.svelte
  apps/penxle.com/src/routes/editor/[permalink]/DraftListModal.svelte
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
Labels: :rocket:

#1615 Alert 컴포넌트 추가
  apps/penxle.com/src/lib/components/Alert.svelte
  apps/penxle.com/src/lib/components/index.ts
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1614 모달 컴포넌트 리뉴얼
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
  apps/penxle.com/src/routes/(default)/[space]/TagManageModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/InstantSettleRevenueModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/MonthlyWithdrawSettingModal.svelte
  apps/penxle.com/src/routes/(default)/me/revenue/VerifySettlementIdentityModal.svelte
Labels: :rocket:

#1618 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/help.penxle.com/package.json
  apps/help.penxle.com/panda.config.ts
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  apps/penxle.io/panda.config.ts
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1601 비공개 스페이스로 변경 시 멤버가 아닌 사용자의 팔로우 해제
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#1627 기본 폰트 높이, 자간 조정
  apps/penxle.com/src/styles/global.ts
Labels: :rocket:

#1628 sm breakpoint 변경
  apps/penxle.com/src/styles/breakpoints.ts
Labels: :rocket:

#1620 유저 메뉴 변경된 레이아웃 사항 반영하기
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
Labels: :rocket:

#1635 TextInput 타입 오류 수정
  apps/penxle.com/src/lib/components/v2/forms/TextInput.svelte
Labels: :rocket:

#1621 메인 헤더 UI 리뉴얼
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/styles/global.ts
Labels: :rocket:

#1622 에디터 헤더 리뉴얼
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1623 에디터 툴바 리뉴얼
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1626 인프라 일부 설정 업데이트
  apps/bedrock/pulumi/aws/route53.ts
  apps/bedrock/pulumi/aws/vpc.ts
  apps/bedrock/pulumi/k8s/kube-system/karpenter.ts
  apps/penxle.com/pulumi/index.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#1630 아이콘만 보여주는 메뉴 컨테이너 가로 너비가 필요 이상으로 늘어져 있어 고침
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1629 메인 피드 리뉴얼 퍼블리싱
  apps/penxle.com/src/lib/components/Tag.svelte
  apps/penxle.com/src/lib/components/tab/TabHead.svelte
  apps/penxle.com/src/routes/(default)/(index)/+layout.svelte
  apps/penxle.com/src/routes/(default)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/(index)/HorizontalScroll.svelte
  apps/penxle.com/src/routes/(default)/(index)/Post.svelte
  apps/penxle.com/src/routes/(default)/(index)/PostCard.svelte
Labels: :rocket:

#1631 정렬 서식 메뉴 내 아이템 버튼에 패딩이 없어서 수정함
  apps/penxle.com/src/lib/components/menu/MenuItem.svelte
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1633 기초적인 job queue 구현
  apps/bedrock/pulumi/aws/mq.ts
  apps/penxle.com/package.json
  apps/penxle.com/src/hooks/server.ts
  apps/penxle.com/src/lib/server/jobs/index.ts
  apps/penxle.com/src/lib/server/jobs/test.ts
  apps/penxle.com/src/lib/server/jobs/types.ts
  apps/penxle.com/src/lib/server/mq.ts
  apps/penxle.com/src/lib/server/utils/index.ts
  apps/penxle.com/src/lib/server/utils/resource.ts
  cspell.config.json
  pnpm-lock.yaml
Labels: :rocket:

#1636 window.innerWidth로 breakpoint 체크하던 부분 수정
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/collections/[entity]/+page@(default).svelte
  apps/penxle.com/src/routes/(default)/me/(index)/+page.svelte
Labels: :rocket:
