Repository penxle/withglyph, pull requests merged in 2024-02, with the labels that each got.

#1160 스테이징과 별개로 개발서버 배포 추가함
  .github/workflows/cd-dev.yml
  apps/bedrock/pulumi/aws/s3.ts
  apps/bedrock/pulumi/k8s/misc/namespaces.ts
  apps/help.penxle.com/pulumi/index.ts
  apps/penxle.com/pulumi/index.ts
  apps/penxle.io/pulumi/index.ts
  packages/pulumi/src/components/site.ts
Labels: :rocket:

#1124 결제선 리뉴얼
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/tiptap/extensions/placeholder.ts
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/index.ts
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/editor/+page.svelte
  apps/penxle.com/src/routes/editor/ArticleFloatingMenu.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#1168 허용된 ip는 점검 중에도 접속할 수 있도록 수정
  apps/penxle.com/src/hooks/handles/maintenance.ts
Labels: :rocket:

#1180 ToggleButton group prop 미 할당 시 나오는 런타임 타입 오류 고치기
  apps/penxle.com/src/lib/components/ToggleButton.svelte
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/ContentFilterButton.svelte
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1178 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1171 ElasticSearch 인덱스 재생성 스크립트
  apps/penxle.com/scripts/create-search-index.ts
Labels: :rocket:

#1186 contentFilters에 의존하는 기능 제거
  apps/penxle.com/scripts/create-search-index.ts
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/search.ts
  apps/penxle.com/src/lib/server/utils/search.ts
  apps/penxle.com/src/routes/(default)/me/settings/contentfilters/+page.svelte
  apps/penxle.com/src/routes/(default)/search/+layout.svelte
Labels: :rocket:

#1183 잘못된 가격으로 발행이 가능한 버그 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1187 PostRevision.title nullable하게 수정
  apps/penxle.com/prisma/migrations/20240201091153_make_post_revision_title_nullable/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/components/PostCard.svelte
  apps/penxle.com/src/lib/components/SpacePostCard.svelte
  apps/penxle.com/src/lib/components/pages/collections/ManageCollectionModal.svelte
  apps/penxle.com/src/lib/components/pages/posts/PostManageTable.svelte
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/PostItem.svelte
  apps/penxle.com/src/routes/(default)/me/cabinets/purchased/+page.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page@(default).svelte
  apps/penxle.com/src/routes/(default)/me/revenue/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/point/+page.svelte
  apps/penxle.com/src/routes/editor/DraftPostModal.svelte
  apps/penxle.com/src/routes/editor/Editor.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
  apps/penxle.com/src/routes/editor/[permalink]/+page.svelte
  apps/penxle.com/src/routes/editor/types/restore-revision.ts
Labels: :rocket:

#1181 createPost시 선택적으로 스페이스를 선택할 수 있도록 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/routes/(default)/Header.svelte
Labels: :rocket:

#1182 스페이스에서 포스트 작성 시 createPost하도록 수정
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/(space)/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
Labels: :rocket:

#1191 외부 검색 허용 버튼 워딩 수정
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1196 서버에서도 제목 부제목 길이 체크
  apps/penxle.com/src/lib/validations/post.ts
Labels: :rocket:

#1198 본문 설정 메뉴에서 현재 선택된 옵션 보여지도록 함
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1197 결제선 무한 증식 버그 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1199 발행한 유료글 수정시 가격 날라가는 이슈 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1200 에디터 툴바 메뉴 포지션 전체적으로 조정
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1201 팁탭 File 노드뷰 컴포넌트에서 파일 이름을 한줄로 제한함
  apps/penxle.com/src/lib/tiptap/node-views/file/Component.svelte
Labels: :rocket:

#1202 결제선이 맨 아래가 아닐 때 가격 없이 발행 시도하면 오류 던지도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1203 제목이나 부제목이 없어도 revisePost 할 수 있도록 수정
  apps/penxle.com/src/lib/validations/post.ts
Labels: :rocket:

#1208 발행옵션 탭 순서 조정
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1209 게시할 스페이스 선택하지 않은 경우 툴팁 메시지 띄움
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1211 컬렉션 id 초기화 안되는 문제 수정
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1213 컬렉션 선택 안함 버튼 추가
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1212 팁팁 루비/링크 편집 메뉴가 해당 위치에 바로 뜨도록 수정
  apps/penxle.com/src/routes/editor/ArticleLinkEditMenu.svelte
  apps/penxle.com/src/routes/editor/ArticleRubyEditMenu.svelte
  apps/penxle.com/src/routes/editor/Header.svelte
Labels: :rocket:

#1214 publishPost 전 revisePost한 revisionId가 반영이 되지 않는 문제 수정
  apps/penxle.com/src/routes/editor/PublishMenu.svelte
Labels: :rocket:

#1218 발행이 된 게 아니라면 스페이스를 변경할 수 있도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1220 게시 옵션 검색 아이콘 삭제
  apps/penxle.com/src/routes/editor/PublishMenuSearch.svelte
Labels: :rocket:

#1231 컬러피커 hex 변수값 대문자로 유지하기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
Labels: :rocket:

#1238 텍스트 선택 영역에서 가장 먼저 설정된 글자 색상으로 일괄 변경되는 문제 고치기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
Labels: :rocket:

#1233 발행 메뉴 내 라디오 버튼 클릭 가능한 영역을 컨테이너로 넓힘
  apps/penxle.com/src/routes/editor/[permalink]/RadioGroup.svelte
Labels: :rocket:

#1232 에디터 툴바 드롭다운 메뉴 버튼 가로 너비 고정하기
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1245 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/bedrock/tsconfig.json
  apps/cashflow/package.json
  apps/cashflow/tsconfig.json
  apps/cashflow/tsup.config.ts
  apps/help.penxle.com/package.json
  apps/help.penxle.com/tsconfig.json
  apps/literoom/package.json
  apps/literoom/tsconfig.json
  apps/penxle.com/package.json
  apps/penxle.com/tsconfig.json
  apps/penxle.io/package.json
  apps/penxle.io/tsconfig.json
  package.json
  packages/adapter-docker/package.json
  packages/adapter-docker/tsconfig.json
  packages/glitch/package.json
  packages/glitch/tsconfig.json
  packages/lib/package.json
  packages/lib/src/deps/index.ts
  packages/lib/tsconfig.json
  packages/lib/tsup.config.ts
  packages/pulumi/package.json
  packages/pulumi/tsconfig.json
  packages/tracing/package.json
  packages/tracing/tsconfig.json
  packages/tsconfig/tsconfig.json
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1246 태그 입력시 정규화
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
Labels: :rocket:

#1248 allowedAgeRating 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1252 15세 포스트에서도 본인 인증 필요 모달 띄우도록 수정
  apps/penxle.com/src/routes/(default)/LoginRequireModal.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1254 스페이스가 지정된 임시저장 포스트의 스페이스를 변경할 수 있도록 수정
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1257 트위터 SSO 연결 지원 추가
  apps/penxle.com/.env
  apps/penxle.com/package.json
  apps/penxle.com/prisma/migrations/20240205091205_add_user_single_sign_on_provider_twitter/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/assets/icons/twitter.svg
  apps/penxle.com/src/lib/server/external-api/index.ts
  apps/penxle.com/src/lib/server/external-api/twitter.ts
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/rest/routes/sso.ts
  apps/penxle.com/src/routes/(default)/me/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/me/settings/UserSingleSignOn.svelte
  pnpm-lock.yaml
Labels: :rocket:

#1258 post.bookmarkGroup 쿼리 최적화
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1256 태그 input blur될 때 태그 등록되도록 수정
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
Labels: :rocket:

#1259 에디터 탑바의 선택된 메뉴 버튼에 pressed 상태 추가
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1260 form.submit 대신 form.requestSubmit 이용하기
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
Labels: :rocket:

#1261 aria-pressed attribute가 버튼에 붙도록 수정
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1249 컬러피커 색상 조정 시 슬라이더 입력 고정하기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
Labels: :rocket:

#1262 게시 옵션 메뉴 디자인 변경사항 반영
  apps/penxle.com/src/assets/icons2/globe.svg
  apps/penxle.com/src/assets/icons2/link.svg
  apps/penxle.com/src/assets/icons2/users.svg
  apps/penxle.com/src/lib/components/ToggleButton.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Chip.svelte
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
  apps/penxle.com/src/routes/editor/[permalink]/RadioGroup.svelte
Labels: :rocket:

#1263 발행버튼 색상 gray 950으로 통일
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1266 에디터에서 스페이스 생성 시 페이지 이동하지 않도록 수정
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1267 발행옵션에서 스페이스에 컬렉션이 없어도 바로 생성할 수 있도록 수정
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1264 팁탭 에디터/렌더러 자잘하게 스타일 수정
  apps/penxle.com/src/lib/tiptap/components/TiptapEditor.svelte
  apps/penxle.com/src/lib/tiptap/components/TiptapRenderer.svelte
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#1272 array 타입 내부에 @_required 를 이용할 경우 타입이 제대로 강제되지 않는 문제 수정
  packages/glitch/src/types.ts
Labels: :rocket:

#1273 불필요한 @ts-expect-error 제거
  apps/penxle.com/src/routes/(default)/(feed)/(index)/+page.svelte
Labels: :rocket:

#1269 스페이스 slug를 포스트에 맞게 replace
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#1276 루트 레이아웃 min-height 100vh에서 100dvh로 변경
  apps/penxle.com/src/routes/+layout.svelte
Labels: :rocket:

#1280 팁탭 gapcursor 보이지 않는 이슈 수정
  apps/penxle.com/src/styles/prose.css
Labels: :rocket:

#1277 atproto txt 레코드 추가
  apps/bedrock/pulumi/aws/route53.ts
Labels: :rocket:

#1265 게시옵션 메뉴 반응형 작업
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1271 사용하지 않는 아이콘 asset 삭제
  apps/penxle.com/src/assets/icons/globe-outline.svg
  apps/penxle.com/src/assets/icons/letter-space.svg
  apps/penxle.com/src/assets/icons/line-height.svg
  apps/penxle.com/src/assets/icons/reply-fill.svg
  apps/penxle.com/src/assets/icons/reply-outline.svg
  apps/penxle.com/src/assets/icons/ruby.svg
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
Labels: :rocket:

#1275 모바일 에디터
  apps/penxle.com/src/assets/icons2/quite-line.svg
  apps/penxle.com/src/assets/icons2/text.svg
  apps/penxle.com/src/lib/tiptap/components/TiptapNodeViewBubbleMenu.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Content.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
  apps/penxle.com/src/routes/editor/[permalink]/MobileEditMenu.svelte
Labels: :rocket:

#1283 게시옵션 메뉴 디자인 변경사항 반영
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenuSearch.svelte
Labels: :rocket:

#1282 구분선 종류 추가 및 크기, 색상 조정
  apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/static/horizontal-rules/8.svg
Labels: :rocket:

#1284 트위터 연동시 스페이스 링크 체크
  apps/penxle.com/prisma/migrations/20240208091032_user_event_settlement/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/src/lib/server/external-api/twitter.ts
  apps/penxle.com/src/lib/server/rest/routes/sso.ts
Labels: :rocket:

#1285 이벤트 참여 조회 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1279 모바일 에디터 동작 개선 및 디자인 추가 반영
  apps/penxle.com/src/lib/tiptap/lib/NodeView.svelte
  apps/penxle.com/src/routes/+layout.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/MobileEditMenu.svelte
  apps/penxle.com/src/routes/editor/[permalink]/MobileToolbarButton.svelte
Labels: preview

#1288 RadioGroup 컴포넌트에서 중복된 id 지정하는 문제 해결
  apps/penxle.com/src/routes/editor/[permalink]/RadioGroup.svelte
Labels: :rocket:

#1287 발행시 포스트 이벤트 조건 체크 추가
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1289 모바일에서 팁탭 노드뷰 터치 스크롤 안 되는 이슈 수정
  apps/penxle.com/src/lib/tiptap/lib/NodeView.svelte
Labels: :rocket:

#1293 포스트 조회수 업데이트 버그 수정
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#1294 포스트 slug redirect 임시 비활성화
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: :rocket:

#1298 글 발행 이벤트 누락분 반영 스크립트 추가
  apps/penxle.com/scripts/202402-event.ts
Labels: :rocket:

#1299 팁탭 Embed 노드뷰에 제목이나 설명 없을 경우 핸들링함
  apps/penxle.com/src/lib/tiptap/node-views/embed/Component.svelte
Labels: :rocket:

#1278 메인 피드 리뉴얼
  apps/penxle.com/src/assets/branding/logo-empty.svg
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
  apps/penxle.com/src/routes/(default)/(feed)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/(index)/+page.svelte
  apps/penxle.com/src/routes/(default)/(index)/+page.ts
  apps/penxle.com/src/routes/(default)/(index)/PostCard.svelte
Labels: preview

#1318 더 이상 사용하지 않은 색상 프리셋 목록 지우기
  apps/penxle.com/src/lib/components/ColorPicker.svelte
  apps/penxle.com/src/lib/tiptap/values.ts
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/MobileEditMenu.svelte
Labels: :rocket:

#1319 현재 선택한 색상 hex 값이 소문자로 저장되는 문제 고치기
  apps/penxle.com/src/routes/editor/[permalink]/Header.svelte
  apps/penxle.com/src/routes/editor/[permalink]/MobileEditMenu.svelte
Labels: :rocket:

#1320 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/cashflow/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/graphql/builder.ts
  apps/penxle.com/src/lib/tiptap/marks/link.ts
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lib/src/vite/config.ts
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview, :rocket:

#1327 팁탭 access_barrier 보존 로직 개선
  apps/penxle.com/src/lib/tiptap/components/TiptapEditor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/index.ts
Labels: :rocket:

#1329 모바일 에디터 발행 버튼 패딩값 수정
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:

#1351 커밋 시 unocss 클래스네임에 공백이 들어가서 포멧팅 제외처리함
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
Labels: :rocket:

#1349 버튼 이름 '닫기'로 변경하기
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
Labels: :rocket:

#1353 TiptapNodeViewBubbleMenu 화면 내에 고정함
  apps/penxle.com/src/lib/svelte/actions/floating.ts
  apps/penxle.com/src/lib/tiptap/components/TiptapNodeViewBubbleMenu.svelte
Labels: :rocket:

#1347 이미지 슬라이드가 보이지 않는 문제 수정
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Display.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Slide.svelte
Labels: :rocket:

#1348 이미지 슬라이드에 간격 추가 옵션 적용
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Display.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Slide.svelte
Labels: :rocket:

#1352 클래스네임 목록이 자동 줄바꿈 포멧팅이 되어 있어 추가로 고침
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
Labels: :rocket:

#1356 팁탭 gallery 노드뷰 사이즈 & 정렬 기능 구현
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Display.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Slide.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/index.ts
Labels: :rocket:

#1354 이미지 드래그 시 자동 스크롤이 더 쉽게 되도록 함
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
Labels: :rocket:

#1355 이미지 목록 모달 디자인 변경사항 반영
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Modal.svelte
Labels: :rocket:

#1361 이미지 에디터 온보딩 스타일 적용안되는 문제 수정
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
Labels: :rocket:

#1365 이메일 입력 타입 어트리뷰트 명시하기
  apps/penxle.com/src/routes/(auth)/login/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/members/+page.svelte
Labels: :rocket:

#1363 온보딩 팝오버 내 일부 unocss 클래스 네임이 알 수 없는 이유로 누락되어 직접 추가함
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
Labels: :rocket:

#1374 로그인 화면 배경 square-full로 설정
  apps/penxle.com/src/routes/(auth)/+layout.svelte
Labels: :rocket:

#1375 정기 디펜던시 업그레이드
  apps/bedrock/package.json
  apps/help.penxle.com/package.json
  apps/literoom/package.json
  apps/penxle.com/package.json
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.io/package.json
  package.json
  packages/adapter-docker/package.json
  packages/glitch/package.json
  packages/lib/package.json
  packages/lintconfig/package.json
  packages/pulumi/package.json
  packages/tracing/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: preview

#1381 게시물 세부공개 비활성화해도 메인 피드에서는 조회수 보이는 문제 수정
  apps/penxle.com/src/routes/(default)/(index)/PostCard.svelte
Labels: :rocket:

#1359 새 디자인시스템 버튼 컴포넌트 추가하기
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/lib/components/v2/index.ts
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
  apps/penxle.com/src/routes/_playground/button/+page.svelte
  apps/penxle.com/src/routes/_playground/button/+page.ts
Labels: :rocket:

#1360 하드코딩한 버튼 스타일링을 새 컴포넌트로 교체하기
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
Labels: :rocket:

#1396 트리거 태그는 최근 사용된 태그에 나오지 않게 수정
  apps/penxle.com/src/lib/server/graphql/schemas/feed.ts
Labels: :rocket:

#1401 포인트 잔액을 종류별로 조회할 수 있도록 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
  apps/penxle.com/src/lib/server/utils/point.ts
  apps/penxle.com/src/routes/(default)/point/+page.svelte
Labels: :rocket:

#1395 이벤트 보상 포인트 지급 스크립트
  apps/penxle.com/prisma/migrations/20240222110117_point_transaction_cause_event/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/scripts/202402-event-reward.ts
  apps/penxle.com/src/routes/(default)/point/+page.svelte
Labels: :rocket:

#1403 포스트 이벤트 체크 코드 제거
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1406 dev/staging 도메인 다시 추가
  apps/penxle.com/pulumi/index.ts
Labels: preview, :rocket:

#1407 이모지 남긴 포스트 목록 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/user.ts
Labels: :rocket:

#1376 댓글 DB
  apps/penxle.com/prisma/migrations/20240223060422_comment/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: DB 마이그레이션 있음

#1408 공유용 이미지에서 펜슬 로고 색상이 텍스트 컬러 따라가도록 함
  apps/penxle.com/src/lib/server/utils/image.ts
Labels: :rocket:

#1411 독자 - 프로필 관계 unique화
  apps/penxle.com/prisma/migrations/20240223093928_masquerade_profile_unique/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:, DB 마이그레이션 있음

#1377 폼 전송 이후에 유효성 검사 결과 표시하기
  apps/penxle.com/src/lib/components/forms/FormValidationMessage.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
Labels: :rocket:

#1296 결제선 값이 유효하지 않을 시 툴팁으로 힌트를 알려주기
  apps/penxle.com/src/lib/components/Tooltip.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/zod.ts
  pnpm-lock.yaml
Labels: preview, :rocket:

#1404 새 디자인시스템 모달 경로 옮기기
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/lib/components/v2/index.ts
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Editor.svelte
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Modal.svelte
Labels: :rocket:

#1389 선택한 텍스트 이미지로 공유하는 기능 리뉴얼
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/routes/(default)/[space]/SelectionBubbleMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
  apps/penxle.com/src/routes/_playground/image-share/+page.svelte
  apps/penxle.com/src/routes/_playground/image-share/+page.ts
  apps/penxle.com/src/routes/_playground/image-share/ShareContent/ColorPicker.svelte
  apps/penxle.com/src/routes/_playground/image-share/ShareContent/ShareContent.svelte
  apps/penxle.com/src/routes/_playground/image-share/ShareContent/index.ts
Labels: preview, :rocket:

#1300 포스트 페이지 리뉴얼
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1402 독자관리 페이지 퍼블리싱
  apps/penxle.com/src/lib/components/tab/TabHeadItem.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/+layout@.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/posts/+layout.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/subscribers/blocked/+page.svelte
Labels: :rocket:

#1412 유저메뉴 퍼블리싱
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/Notification.svelte
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
Labels: :rocket:

#1413 포스트 모바일 헤더, 푸터 변경
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/Header.svelte
Labels: :rocket:

#1421 다중 깊이 댓글이 생기지 않도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1422 문장 공유 기능 재활성화
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/SelectionBubbleMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/ShareContent.svelte
Labels: :rocket:

#1423 gql 비밀 댓글 처리
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1416 포스트 댓글 권한 세분화
  apps/penxle.com/prisma/migrations/20240223133529_post_comment_qualification/migration.sql
  apps/penxle.com/prisma/schema.prisma
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
Labels: :rocket:, DB 마이그레이션 있음

#1415 독자 차단 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#1419 댓글 프로필 미리보기 gql 필드
  apps/penxle.com/src/lib/server/graphql/schemas/space.ts
Labels: :rocket:

#1420 독자 차단 gql 연결
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/routes/(default)/[space]/dashboard/subscribers/blocked/+page.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/subscribers/blocked/+page.ts
Labels: :rocket:

#1428 댓글 조회 오류 수정
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1427 포스트 하단 관심 스페이스 토글 버튼 모바일에서 줄바꿈해서 보여주기
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1429 포스트 상단 헤더 마크업 미스매치 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1433 삭제 댓글 리턴 조건 수정
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1430 gray 150 색상 추가
  packages/lib/src/unocss/colors.ts
Labels: :rocket:

#1431 font-weight light 추가
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#1432 알림 디자인 변경사항 반영
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/Header.svelte
  apps/penxle.com/src/routes/(default)/me/notifications/+page@.svelte
Labels: :rocket:

#1434 댓글 고정 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1435 댓글 좋아요 db
  apps/penxle.com/prisma/migrations/20240227044101_post_comment_like/migration.sql
  apps/penxle.com/prisma/schema.prisma
Labels: :rocket:, DB 마이그레이션 있음

#1436 댓글 좋아요 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1437 댓글 구매자인지 여부 필드 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1441 피드 페이지에서 오버플로우 되는 문제 고치기
  apps/penxle.com/src/routes/(default)/(index)/PostCard.svelte
Labels: :rocket:

#1442 포스트 태그만 업데이트 뮤테이션
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1444 페이지네이션용 댓글 갯수 추가
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/post.ts
Labels: :rocket:

#1445 댓글 내가 좋아요 눌렀는지 여부 필드
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1443 버튼 컴포넌트 스타일 업데이트
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/routes/_playground/button/+page.svelte
Labels: :rocket:

#1438 포스트 공유 팝오버 UI 구현하기
  apps/penxle.com/src/lib/tiptap/node-views/gallery/Slide.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/SharePostPopover.svelte
  packages/lib/src/unocss/box-shadow.ts
  packages/lib/src/unocss/preset.ts
Labels: :rocket:

#1439 공유 버튼에 호버 스타일 추가하기
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1440 댓글 알림 gql
  apps/penxle.com/schema.graphql
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
  apps/penxle.com/src/lib/server/graphql/schemas/notification.ts
  apps/penxle.com/src/lib/server/rest/routes/notification.ts
  apps/penxle.com/src/lib/utils/notification.ts
Labels: :rocket:

#1426 댓글 gql 연결
  apps/penxle.com/src/lib/glitch/updates.ts
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
  apps/penxle.com/src/routes/(default)/[space]/CommentInput.svelte
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/Reply.svelte
  apps/penxle.com/src/routes/(default)/[space]/ReplyInput.svelte
  apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
Labels: preview, :rocket:

#1446 포스트 ui 변경사항 반영
  apps/penxle.com/src/lib/emoji/EmojiPicker.svelte
  apps/penxle.com/src/routes/(default)/Header.svelte
  apps/penxle.com/src/routes/(default)/NotificationMenu.svelte
  apps/penxle.com/src/routes/(default)/SearchBar.svelte
  apps/penxle.com/src/routes/(default)/UserMenu.svelte
  apps/penxle.com/src/routes/(default)/[space]/AlertText.svelte
  apps/penxle.com/src/routes/editor/[permalink]/Content.svelte
Labels: :rocket:

#1447 tiptap css 오타 수정
  apps/penxle.com/src/lib/tiptap/node-views/gallery/driver.css
Labels: :rocket:

#1448 포스트 페이지 내 태그 관리 기능 구현하기
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/lib/validations/post.ts
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
  apps/penxle.com/src/routes/(default)/[space]/TagManageModal.svelte
Labels: :rocket:

#1450 댓글 pagination 임시 비활성화
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1451 댓글 관련 mixpanel 이벤트 이름 전체적으로 수정
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
  apps/penxle.com/src/routes/(default)/[space]/dashboard/subscribers/blocked/+page.svelte
Labels: :rocket:

#1452 컬렉션 기준 앞뒤 포스트 구현
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1454 포스트 헤더 내 공유 아이콘이 작은 크기로 잘못 들어가서 수정함
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:

#1453 자신이 단 댓글은 알림이 가지 않도록 수정
  apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
Labels: :rocket:

#1449 모달 콘텐츠 분량이 뷰포트를 벗어날 정도로 많은 경우 잘리는 문제 고치기
  apps/penxle.com/src/lib/components/v2/Modal.svelte
Labels: :rocket:

#1455 포스트 공유 팝오버 UI가 본문에 가려지는 문제 고치기
  apps/penxle.com/src/routes/(default)/[space]/SharePostPopover.svelte
Labels: :rocket:

#1459 포스트 구매 모달 ui 변경
  apps/penxle.com/src/lib/tiptap/node-views/access-barrier/Component.svelte
Labels: :rocket:

#1463 독자 차단 모달 추가
  apps/penxle.com/src/lib/components/v2/Button.svelte
  apps/penxle.com/src/lib/components/v2/Modal.svelte
  apps/penxle.com/src/routes/(default)/[space]/Comment.svelte
Labels: :rocket:

#1464 태그 수정 버튼 오타 수정
  apps/penxle.com/src/routes/(default)/[space]/Post.svelte
Labels: :rocket:
